### ISSUE TITLE
New Merchant Tutorial

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#1]
# User Story
As a new Easy Paywall merchant, I would like to be guided through how to use the plugin the first time I click through.

# Description
The plugin Tutorial is a series of help screens that will walk the merchant through the features available in the new plugin.

# Acceptance Criteria
- The article visible in the background should be the most recently published article.
- ~~If a merchant clicks the screen (outside the tutorial, it should progress the tutorial)~~
- A new merchant should be walked through the following screens after
  - They choose an option on the Welcome screen or 
  - Clicking the `Tutorial` button on the Paywall Dashboard

Step | Notes | Designs
-- | -- | --
Pre-tutorial animation | Begins after choosing an option on the Welcome screen | [Prototype](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=161%3A11070&scaling=scale-down-width&scaling=scale-down-width) - [Design Specs 1](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3b3270aa2775c7011c3256) - [Design Specs 2](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3b3270fb4c0990924fafb4)
Find Article |The article visible in the background of the tutorial should be the most recently published article | [Prototype](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=7%3A5524&scaling=scale-down-width) - [Design Specs](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3b335bf14152ce07dc7e9c)
Edit Purchase Option | | [Prototype](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=7%3A6194&scaling=scale-down-width) - [Design Specs](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3b335b34b67a8cd9eb654d)
More Options | | [Prototype](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=7%3A6889&scaling=scale-down-width) - [Design Specs](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3b335b632fc6b4bc7ba30d)
Edit Purchase Option Text | | [Prototype](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=7%3A6712&scaling=scale-down-width) - [Design Specs](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3b335be3d1200d8e0638f3)
Edit Pricing | | [Prototype](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=7%3A7066&scaling=scale-down-width) - [Design Specs](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3b335b5f5ec89adf786741)
Add Purchase Option | | [Prototype](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=11%3A0&scaling=scale-down-width) - [Design Specs](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3b335b0e29288db296668b)
Name Paywall | | [Prototype](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=11%3A1130&scaling=scale-down-width) - [Design Specs](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3b335cc1697b0a106fae5a)
Define Content | | [Prototype](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=7%3A5815&scaling=scale-down-width) - [Design Specs](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3b335b953e58b5ee0f5a35)
Publish Paywall| | [Prototype](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=11%3A1391&scaling=scale-down-width) - [Design Specs](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3b335cdac191cca7878a0a)

**Comment by thrijith** [comment]
> If a merchant clicks the screen (outside the tutorial, it should progress the tutorial)

@ksmoore125 since the preview is being added on actual content, I've disabled events when in tutorial, so this won't work, if this is required the merchant will be able to interact with elements while in preview, which should not happen.

Please let me know if it would be possible to skip this.

**Comment by ksmoore125** [comment]
@thrijith - Yes, we can skip that; I will strikeout from the requirements.

**Comment by ksmoore125** [comment]
@thrijith -
> have spoken to the LaterPay team and in the first version of LaterPay OnPage, the merchant will not be able to customize the paywall header or description [comment here](https://github.com/laterpay/revenue-generator/issues/3#issuecomment-601401693)

We will also need to [remove this step from the tutorial](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3b340df80ad2935ccb91ff).

**Comment by ksmoore125** [comment]
A few minor edits are outlined below:


Description | Plugin Screenshot | Design
-- | -- | --
On the first screen of the tutorial, the purchase options are highlighted when they should not be|![image](https://user-images.githubusercontent.com/41650164/77326568-fad91f80-6ce7-11ea-8630-8dafbc993bb0.png)| ![image](https://user-images.githubusercontent.com/41650164/77326690-2bb95480-6ce8-11ea-8403-cb5838c24b1c.png) [here](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3b335bf14152ce07dc7e9c)
Add line break between "prices." and "Click" | ![image](https://user-images.githubusercontent.com/41650164/77191936-bf511200-6aa9-11ea-8b30-3ab444a63c01.png) | ![image](https://user-images.githubusercontent.com/41650164/77191979-d42da580-6aa9-11ea-9fd3-b18919227deb.png) [here](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3b335b5f5ec89adf786741)
"Click here to change the name of your paywall" points to the wrong place | ![image](https://user-images.githubusercontent.com/41650164/77192107-0939f800-6aaa-11ea-9cc1-fd539a1e6299.png) | ![image](https://user-images.githubusercontent.com/41650164/77192129-13f48d00-6aaa-11ea-93d5-abf790e8cdbb.png) [here](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3b335cc1697b0a106fae5a)
Edit Tutorial button should be in line with the footer |
![image](https://user-images.githubusercontent.com/41650164/77342419-25ce6e00-6cfe-11ea-952b-618c0bc8c832.png) | ![image](https://user-images.githubusercontent.com/41650164/77342572-63cb9200-6cfe-11ea-93b0-a5eb7d469c54.png)

**Comment by ksmoore125** [comment]
Description | Plugin Screenshot
-- | --
After the first screen, it jumped down too far and I can no longer read the next tutorial step | ![image](https://user-images.githubusercontent.com/41650164/77471377-293a2600-6de0-11ea-9787-7b3bba6d47e7.png) 
Add a line break after the description so that there is some space above the NEXT button | ![image](https://user-images.githubusercontent.com/41650164/77471448-4f5fc600-6de0-11ea-80e4-93e15915159c.png)

**Comment by thrijith** [comment]
@ksmoore125 I was unable to replicate first issue mentioned above, tested on several [screen sizes](https://drive.google.com/open?id=10mJcxAQKCqoP5-tncRBY9E5_BLh6MUFT), were you able to scroll above and see if you were able to navigate to read the info?

**Comment by ksmoore125** [comment]
I was able to scroll and was not able to reproduce today so it looks like the issue is resolved.
