### ISSUE TITLE
API Credentials do not appear to be Stored Unless you Navigate to the Dashboard

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#100]
**Steps to Reproduce**
- Start with a fresh install of the plugin
- Create a paywall
- Click `Publish`
- Enter valid merchant credentials
- Close the modal
- Make changes
- Click `Publish`

**Observed Result**
You are asked for your credentials again 
See 3:15-4:30 in [this video](https://laterpay.slack.com/archives/C02JCERA4/p1588183518000200)

**Desired Result**
You credentials should have been stored and therefore you should not have to enter them again

**Comment by milindmore22** [comment]
@ksmoore125 Unable to reproduce this issue

**Comment by ksmoore125** [comment]
I have experienced this a few different times but unfortunately it appears to be intermittent so I am not sure the best way to consistently reproduce.

One thing that also happened to me twice:
- Start with a fresh install of the plugin
- Setup & Publish a paywall
- Enter your credentials
- See the loading screen
- See the enter credentials screen ❌ 
- See the Published paywall screen
