### ISSUE TITLE
`View on live post` takes you to a Post without the Paywall

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#101]
**Steps to Reproduce**
- Create a new Paywall
- Choose to preview a `Post A` which is in `Category A` (for example)
- Configure the paywall
- Select that the paywall should apply to `Category B`
- Publish the paywall
- Choose to `View on live post`

**Observed Result**
You are taken to `Post A` which does not have that paywall on it
See 3:05-3:45 in [this video](https://laterpay.slack.com/archives/C02JCERA4/p1588183518000200)

**Expected Result**
You should be taken to a Post which has the paywall regardless of if it was the one that you were previewing

**Comment by milindmore22** [comment]
@ksmoore125 

I have considered the following cases, let me know in case I miss any.

Assumtions : Post A -> Cateogry A ...

Case 1: If `Post A` is for Preview and `Category A` is selected.
 it will preview Post A

Case 2: If `Post B` is chosen and `Category A` is selected
It will look for Post for with Category A and Preview it

Case 3: `Post C` is Chosen `No Category` is selected 
Preview Post C

Case 4: `Post D` is chosen and `Category E` is selected ( Category E is not assigned to any post )
Previews Post D ( in this case we can not display paywall as it is assigned to the category with no posts )

**Comment by ksmoore125** [comment]
@milindmore22 - That sounds good, thanks!
