### ISSUE TITLE
Paywall not Publishing after clicking Publish

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#102]
**Steps to Reproduce**
- Set up a fresh install of the plugin
- Go through the tutorial
- Click `Publish`
- Click `Signup`
- Enter valid merchant credentials

**Observed Result**
Even though I clicked publish, the paywall is saved, not published

**Desired Result**
The paywall should save & publish

**Comment by milindmore22** [comment]
@ksmoore125 tested this several times but unable to reproduce
