### ISSUE TITLE
Publish to WordPress Plugin Store

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#103]
- Create [public facing readme](https://docs.google.com/document/d/18qrOaGIIca8YJqERH_fD1CS2wOJ6ceqN9XygERpssFQ/edit?ts=5e8ad753)
- Get review by WordPress team
- Make any necessary changes
- Go live!

**Comment by ksmoore125** [comment]
Given that OnPage is almost done. We should likely update our integration first. Exact requirements TBD.

**Comment by milindmore22** [comment]
@ksmoore125 JFI:  we don't have [FAQ](https://wordpress.org/plugins/jetpack/#faq-header) section in readme file it's not needed but recommended.

**Comment by ksmoore125** [comment]
We can use these to start with and then add more once we get feedback on the plugin. You can use these exact questions & answers. Let me know if you need anything else!
- [What is LaterPay?](https://support.laterpay.net/what-is-laterpay)
- [How does LaterPay work?](https://support.laterpay.net/how-does-laterpay-work-1)
- [What does LaterPay cost?](https://support.laterpay.net/what-does-laterpay-cost)
