### ISSUE TITLE
Merchant Usage Analytics & Feedback

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#11]
# User Story
As a LaterPay employee, I want to know which parts of the product are or are not working so that we can continue to improve.

# Acceptance Criteria

GA Event Category | GA Event Action | GA Event Label 
-- | -- | -- 
LP RevGen | Welcome Landing Page | `Contributions` `Paywall`
LP RevGen Paywall Tutorial | Paywall Landing Page | `Fewer than 10` `10+`
LP RevGen Paywall Tutorial | 1 - Article Search | `Continue` `Exit Tour` 
LP RevGen Paywall Tutorial | 2 - Name Paywall | `Continue` `Exit Tour` 
LP RevGen Paywall Tutorial | 3 - Element Hover | `Continue` `Exit Tour` 
LP RevGen Paywall Tutorial | 4 - More Options | `Continue` `Exit Tour` 
LP RevGen Paywall Tutorial | 5 - Text Edit | `Continue` `Exit Tour` 
LP RevGen Paywall Tutorial | 6 - Pricing | `Continue` `Exit Tour`
LP RevGen Paywall Tutorial | 7 - Add Purchase Option | `Continue` `Exit Tour` 
LP RevGen Paywall Tutorial | 8 - Name Paywall | `Continue` `Exit Tour` 
LP RevGen Paywall Tutorial | 9 - Select Content | `Continue` `Exit Tour` 
LP RevGen Paywall Tutorial | 10 - Publish | `Complete` `Exit Tour` 
LP RevGen Paywall Preview | Article Search | 
LP RevGen Paywall Publish | Save | `Merchant ID` - `Paywall ID` - `Paywall Name` - `Applies to` - `count categories or articles` - `count purchase options`
LP RevGen Paywall Publish | Publish | `Merchant ID` - `Paywall ID` - `Paywall Name` - `Applies to` - `count categories or articles` - `count purchase options`
LP RevGen Paywall Publish | Paywall Details | _The following should have one event per item on the paywall_
LP RevGen Paywall Publish | Paywall Details | `Merchant ID` - `Paywall ID` - Single Article - `Type` (if dynamic say "Dynamic" else "Pay Now" or "Pay Later") - `Price` (if dynamic then "Dynamic") 
LP RevGen Paywall Publish | Paywall Details | `Merchant ID` - `Paywall ID` - `Time Pass` or `Subscription` - `Pay Now` or `Pay Later` - `Duration` - `Price`
LP RevGen Paywall Publish | Conflict | 
LP RevGen Account | Connect Account | `Connect Account` or `Signup`
LP RevGen Account | Connect Account |`Success` or `Failure` - `Error Message` 
LP RevGen Configure Paywall | Edit Title | `Paywall Name` - `Paywall Title` 
LP RevGen Configure Paywall | Paywall Deleted | `Paywall Name` 
LP RevGen Configure Paywall Purchase Options | Help | `Pay Now v Pay Later` `Static Pricing v Dynamic Pricing` 
LP RevGen Contributions Tutorial | 1 - Text Edit | `Continue` `Exit Tour` 
LP RevGen Contributions Tutorial | 2 - Amount Edit | `Continue` `Exit Tour` 
LP RevGen Contributions Tutorial | 3 - PN v PL | `Continue` `Exit Tour` 
LP RevGen Contributions Tutorial | 4 - Campaign Name | `Continue` `Exit Tour` 
LP RevGen Contributions Tutorial | 5 - Generate Code | `Complete` `Exit Tour` 
LP RevGen Contributions | New ShortCode | `Merchant ID` - `Campaign Name` - `Amount 1` - `Amount 2` - `Amount 3`
LP RevGen Contributions | Help | `Campaign name` `Thank you page` `Generate code`

**Comment by ksmoore125** [comment]
From @thrijith:
> we might need a setting to opt in/out check box ...
https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#7-plugins-may-not-track-users-without-their-consent

**Comment by ksmoore125** [comment]
@thrijith - We had planned on adding a Setting page with a checkbox similar to what we have in the LaterPay plugin in v2 so I will just move this ticket to v2 and we can wait to track usage until they have an easy way to optout.

**Comment by ksmoore125** [comment]
Now that we have added Contributions into the plugin, I need to update this to include those flows as well (or create another ticket to address that area)

**Comment by milindmore22** [comment]
@ksmoore125 

I am little bit confused here, can you please provide more details on the following events, when Should they trigger 

GA Event Category | GA Event Action | GA Event Label | triggers on
-- | -- | -- | --
LP RevGen Paywall Publish | Save | `Merchant ID` - `Paywall ID` - `Paywall Name` - `Applies to` - `count categories or articles` - `count purchase options` | User Clicks on _Save Draft_ button Saves Paywall
LP RevGen Paywall Publish | Publish | `Merchant ID` - `Paywall ID` - `Paywall Name` - `Applies to` - `count categories or articles` - `count purchase options` | User Click on _Publish_ button and Publishes Paywall
LP RevGen Paywall Publish | Paywall Details | _The following should have one event per item on the paywall_ | ?
LP RevGen Paywall Publish | Paywall Details | `Merchant ID` - `Paywall ID` - Single Article - `Type` (if dynamic say "Dynamic" else "Pay Now" or "Pay Later") - `Price` (if dynamic then "Dynamic")  | ?
LP RevGen Paywall Publish | Paywall Details | `Merchant ID` - `Paywall ID` - `Time Pass` or `Subscription` - `Pay Now` or `Pay Later` - `Duration` - `Price` | ?
LP RevGen Paywall Publish | Conflict |  |?

**Comment by ksmoore125** [comment]
You may disregard "Conflict" since we removed that feature from the initial release.

The first event in the table above (LP RevGen Paywall Publish - Save) should be triggered when a merchant clicks the `Save` button on the Paywall screen

All of the other items should be triggered when the Paywall is Published or when the merchant clicks the `Publish` button.

**Comment by ksmoore125** [comment]
Please use `UA-50448165-9`

**Comment by ksmoore125** [comment]
@milindmore22 - Please use `UA-50448165-9` (it appears that it is still set to `UA-126481240-1` which I do not have access to therefore I cannot test the events)

**Comment by milindmore22** [comment]
@ksmoore125 
it seems WordPress option value for tracking code is not getting deleted properly, I will check it, 
Can you please create a task to `update option value` for tracking on next plugin release `Update Laterpay Tracking code`  
Currently, we have nothing stored in settings as WordPress plugin review team asked us to remove the value.

**Comment by ksmoore125** [comment]
@milindmore22 - Do you have instructions on how I can test this now? Or do I need to wait to product check this until https://github.com/laterpay/revenue-generator/issues/219 is complete?

**Comment by milindmore22** [comment]
Hello @ksmoore125,

No need to wait for #219 , I will work on it before next release, keeping it to the last task before release just in case we ran into more option/data updates before version updates.

Steps to Test Analytics : 

1. enable later pay Google Analytics 
![image](https://user-images.githubusercontent.com/1132541/86720620-d446b680-c042-11ea-8d56-9ff83083b61e.png)

2. Login to [Google Analytics](https://analytics.google.com/) with an account having access to `UA-50448165-9`

3. open menu on left sidebar for **Realtime** events
![image](https://user-images.githubusercontent.com/1132541/86721291-76669e80-c043-11ea-9be1-d362c595881c.png)

4. Check **Realtime -> Events**, they should fire on Event Occureance ( as you click on test site event will appear here ) as listed in the task above. ( you can toggle in between Current Event and / Last 30 min Events )
![image](https://user-images.githubusercontent.com/1132541/86721424-98602100-c043-11ea-81cd-c3ebeab69588.png)

5. Once Enough Data is generated ( for day/week/month etc) you can get the report from **Behaviour -> Events**
![image](https://user-images.githubusercontent.com/1132541/86722089-381daf00-c044-11ea-846d-5fcecabdd166.png)

Hope this helps, let me know in case you need more details

**Comment by ksmoore125** [comment]
Product check notes:
## Item 1: `GA Event Category` = `Revenue Generator`
There is and event for `GA Event Category` = `Revenue Generator` and `GA Event Action` = `View Dashboard`
For consistency, can we update this to:

GA Event Category | GA Event Action | GA Event Label
-- | -- | --
LP RevGen | View Dashboard | `Contributions` or `Paywall`


## Item 2: Tutorial Events
`GA Event Category` = `LP RevGen Paywall Tutorial` events should be triggered with each step of the tutorial. When testing it appeared that `8 - Name Paywall` `9 - Select Content` and `10 - Publish` were triggered twice even though I only went through the tutorial once today (and I am not sure how those could be triggered twice without the others also being triggered twice)

There appeared to be a similar issue with `LP RevGen Contributions Tutorial` `5 - Generate Code`

_It looks like you were testing as well; perhaps you were testing around midnight and that caused this issue?_
![image](https://user-images.githubusercontent.com/41650164/87089457-136c3780-c1fc-11ea-8232-e7aae6b7ffc7.png)


## Item 3: `LP RevGen Paywall Publish` `Paywall Details`
These events are missing; let me know if you need additional information on what these should be and when they should be triggered.


## Item 4: `LP RevGen Configure Paywall Purchase Option`
For consistency, can we update `GA Event Category` = `LP RevGen Configure Paywall Purchase Option` to `LP RevGen Configure Paywall`
