### ISSUE TITLE
Thank you page box is highlighted in red even though it is not required

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#118]
**Steps to Reproduce**
1. Create a new Contribution box
2. Click in the `Campaign name` box
3. Click in the `Thank you Page` box
4. Click out of the `Thank you Page` box

**Observed Result**
![image](https://user-images.githubusercontent.com/41650164/81438540-93a9ea00-9132-11ea-94e7-a0bf97e56177.png)

**Expected Result**
- Since `Campaign name` is required, it makes sense that it should be highlighted in red when empty
- Since the `Thank you Page` is optional, it should not be highlighted red when empty

**Comment by milindmore22** [comment]
JFI : I am updating code so it will add red highlight when there some input (removing empty check ) and it's an invalid URL on focusout.
