### ISSUE TITLE
Paywall Functionality

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#12]
# Description
One of LaterPay's core functionalities is generating paywalls. That is pretty much the only feature available in v1 of this plugin. Our goal is to allow for significant flexibility to the merchant while at the same time, hiding the complexity.

# How it works in the LaterPay plugin
- Merchant configures `purchase options` for the pay wall (individual purchase, time pass(es), subscription(s)) separately and what they should `provide access` to
- On the post all items that could `provide access` to that article are aggregated and combined to form the paywall

### Why Change?
- It is currently difficult to maintain.
  - It is hard for a merchant to easily determine what content has what prices. _What will show up on my "Political" articles?_
  - It is difficult to know exactly what a paywall will look like. Depending on the category structure of a site, a merchant could easily accidentally create a paywall with 5+ purchase options which is not ideal.
- It does not align with how our customers think/work.
  - When a publisher is setting up the paywall, they typically think about all the prices for a group of content together as opposed to individually (how they must configure it today).

# Revenue Generator
In the Revenue Generator plugin, we want to allow merchants to configure an entire paywall at one time via a visual interface so that they know exactly what their customers will see for a group of content.

### Challenges
Although we want merchants to be able to configure everything together, each `purchase option` often has a different purpose.
- Single article prices vary significantly throughout the site
- Time passes may also vary by types of content
- 85% of subscriptions in the current plugin apply to the entire site

**Proposed Solution**
We architect the new plugin for maximum flexibility behind the scenes and impose limitations only in the UI.
In the LaterPay plugin we have 2 elements `purchase options` and what those options `provide access` to
I propose that in the Revenue Generator we have 3 elements `purchase options` and what those options `provide access` to + `appear on`

By adding `appear on` we allow the merchant to (in future versions) configure their paywalls so that specific user roles see different paywalls than others, for example.

In v1 of the Revenue Generator, our approach will be:
- Single articles `provide access` = `appear on`
- Time passes `provide access` = all content | `appear on` is defined per paywall (#7 )
- Subscriptions `provide access` = all content | `appear on` is defined per paywall (#7 )

In the near future, we would allow Time passes and Subscriptions to have 
`provide access` = all content or `provide access` = `appear on`

[**Design Specs Here**](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e4deac2497bf47c22d456e0)

**Comment by thrijith** [comment]
Individual article access scenarios ( Single articles provide access = appear on )

![Screenshot 2020-02-07 at 12 03 08 PM](https://user-images.githubusercontent.com/13589980/74008290-6ff5cd00-49a6-11ea-813a-d5f5fcfbb7fa.png)

Consider above paywall, let us assume the merchant has selected post

![Screenshot 2020-02-07 at 12 39 18 PM](https://user-images.githubusercontent.com/13589980/74008450-df6bbc80-49a6-11ea-8f0c-53aae935cc4c.png)

- Time Passes and Subscriptions added on this Paywall will provide access to all content in `v1`?

- These Passes and Subscriptions will be stored individually and have attributes that define what they provide access to and what they should appear on?

- When a new Paywall is added for a post or category, the previously created passes and subscriptions will be added automatically?

- Editing / Deleting a Time Pass / Subscription on a Paywall that affect all Paywalls where they are used?

**Comment by ksmoore125** [comment]
@thrijith -
> Time Passes and Subscriptions added on this Paywall will provide access to all content in v1?
Yes

> These Passes and Subscriptions will be stored individually and have attributes that define what they provide access to and what they should appear on?
That is one idea but feel free to use a different implementation method if you would prefer 

> When a new Paywall is added for a post or category, the previously created passes and subscriptions will be added automatically?
Yes

> Editing / Deleting a Time Pass / Subscription on a Paywall that affect all Paywalls where they are used?
Yes; additionally we will need a warning screen to let the merchant know. I will work with our design team to get that included before we get too far along.

**Comment by ksmoore125** [comment]
If a merchant tries to edit a Time Pass or Subscription we should display the following error message:
![image](https://user-images.githubusercontent.com/41650164/74863901-46c52d00-5314-11ea-8a5d-eeac279bed6f.png)

**Comment by ksmoore125** [comment]
If a merchant tries to edit a Time Pass or Subscription we should display the following error message:
![image](https://user-images.githubusercontent.com/41650164/74863901-46c52d00-5314-11ea-8a5d-eeac279bed6f.png)
