### ISSUE TITLE
It is Possible to Publish a Paywall applied to a category without a category selected

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#123]
**To Reproduce**
1. Create a new paywall
2. Select that it should apply to `category` or `except for category`
3. Click `Save` or `Publish`

**Expected Result**
The merchant should be prompted to select a category

**Actual Result**
![image](https://user-images.githubusercontent.com/41650164/81441186-ec7b8180-9136-11ea-9960-a321464b7b95.png)

**Comment by milindmore22** [comment]
@ksmoore125 
The existing mechanism disables **_Save_** button until category is selected. same should be applied for **_Publish_** button right?

**Comment by ksmoore125** [comment]
@milindmore22 - Correct.

**Comment by ksmoore125** [comment]
**Product Check Feedback:** This is working great; would you mind updating the style of the `Save Draft` button to match the [design specs here](https://app.zeplin.io/project/5e3b2d056723900961109141/styleguide/components?coid=5e3c2d992b16c49590aa5069)? (The button outline should be grey instead of black)

Design | Actual
-- | -- 
![image](https://user-images.githubusercontent.com/41650164/82489490-5b49ca80-9aa7-11ea-85cb-3f3c1135583e.png) | ![image](https://user-images.githubusercontent.com/41650164/82489506-6270d880-9aa7-11ea-9a1b-752871c4c708.png)
