### ISSUE TITLE
Paywall Header & Footer Styling Off

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#124]
# Description
- Header and footer should have the same width: https://zpl.io/advEmxl
- Currently the header and footer change width based on the browser width (see table below); instead, these should be a fixed with as shown in the designs here
- Search bar padding & box shadow should match the design [here](https://app.zeplin.io/project/5e3b2d056723900961109141/styleguide/components?cseid=5e3c2ee1632fc6b4bc7fb5f1)

 Narrow Browser | Normal Browser | Wide Browser
-- | -- | --
![image](https://user-images.githubusercontent.com/41650164/81441749-ef2aa680-9137-11ea-960f-8ee1392d30ed.png) | ![image](https://user-images.githubusercontent.com/41650164/81441736-e6d26b80-9137-11ea-89ce-d583fd37dc41.png) | ![image](https://user-images.githubusercontent.com/41650164/81441697-da4e1300-9137-11ea-88a7-643dee603930.png)

**Comment by milindmore22** [comment]
@ksmoore125 
> Search bar padding & box shadow should match the design 

I am a little confused here regarding box-shadow, What should we do with border below input box

![image](https://user-images.githubusercontent.com/1132541/84871507-3e9cb480-b09e-11ea-9399-fd03fbb1bdd5.png)

**Comment by CaterinaFinelli** [comment]
HI @milindmore22 ! please have a look at this screen here https://zpl.io/b6mYW8W
and zoom in to enlarge the search bar, so you can compare it to the implemented version and fix the shadow, the paddings within the text and the bar box. 
this is the CSS snippet for the implementation of the sidebar: `.navbar_previewing {
  width: 588px;
  height: 45px;
  -webkit-backdrop-filter: blur(10px);
  backdrop-filter: blur(10px);
  background-color: rgba(255, 255, 255, 0.9);
}`

thanks!
