### ISSUE TITLE
Allow for Selection of Multiple Categories

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#14]
# User Story
As a LaterPay merchant, I would like to specify that a paywall can apply to one **or more** categories.

# Acceptance Criteria
* Allow a merchant to select multiple categories in the `category` or `except for` selection ([shown here](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e5d4b554085d175a85a8aed))

Relates to: https://github.com/laterpay/revenue-generator/issues/7, https://github.com/laterpay/revenue-generator/issues/20, https://github.com/laterpay/revenue-generator/issues/18

**Comment by ksmoore125** [comment]
**Product Check Notes:**
- When I click `View on live post` I am taken to the previewed post; I should be taken to a post which has that paywall on it (if that paywall does not apply to the previewed post)
- The paywall appears on some **pages** and not others. Since, to the best of my knowledge, **pages** do not have categories, these paywalls should not appear on any **page**.

**Comment by milindmore22** [comment]
> The paywall appears on some pages and not others. Since, to the best of my knowledge, pages do not have categories, these paywalls should not appear on any page.

I am unable to reproduce this on my local, even after importing data from demo site, let me know steps to reproduce the issue. however, I have added potential fix which will block categories and excluded categories for pages.
