### ISSUE TITLE
Make Contributions Editable

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#147]
**Kimberly Moore**
> I was in discussions with a non-technical subset of the LaterPay team and they struggled to understand why we are not letting the merchant update the Contributions shortcode.
I explained that this is because, if they already copy & pasted the shortcode on to their site, the code they copied will not auto-update.
Just out of curiosity, is there a different WordPress tool (widget, etc) where the merchant could update the contribution offer and have it automatically update anywhere they have included it in their site? Or is this functionality that we would need to build out if we wanted to go this direction?

**Milind More**
> Yes, that is correct the shortcode will not auto update on posts or page
In theory there is way we can achieve but it might change shortocde too (edited) 
...
since we are storing contributions in custom post type, there is way to retrieve each shortcode uniquely
instead of adding shortcode options we can fetch them on the fly with post id
so insted of
`[laterpay_contribution  name="Support Milind" thank_you="http://laterpay.test/hello-world/" type="multiple" custom_amount="0" all_amounts="50,100,500" all_revenues="ppu,ppu,sis" selected_amount="1" dialog_header="Support Me!!" dialog_description="Please help me buy essentials"]`
we will have to add
`[laterpay_contribution id="123"]`
...
now if user updates that contribution it will affect on all pages, post and widget etc
...
Also there is possibility to add overrides eg:
`[laterpay_contribution id="123" dialog_header="Support Me!!"]`

[Reference](https://rtcamp.slack.com/archives/GA2P84GBZ/p1589988621003800)

**Comment by tomasstark** [comment]
@ksmoore125 I agree with @milindmore22's approach here. That seems to be the most sensible option. Since we have all data stored in custom post type, there's no need for lengthy shortcodes anyway. But we should still support all those attributes anyway to allow overrides as Milind pointed out.

Just a little heads up – this will only apply to shortcodes generated after the code is deployed. That means if you already have this shortcode in your content:

```[laterpay_contribution name="Support Milind" thank_you="http://laterpay.test/hello-world/" type="multiple" custom_amount="0" all_amounts="50,100,500" all_revenues="ppu,ppu,sis" selected_amount="1" dialog_header="Support Me!!" dialog_description="Please help me buy essentials"]```

It won't reflect updates you do to the contribution unless you change that shortcode to include `id` attribute. That means changing it to something like this:

```[laterpay_contribution id="123"]```

Is that acceptable?

Let me know!

**Comment by ksmoore125** [comment]
@tomasstark - That sounds great. Based on the google analytics usage data, I don't think anyone has created a contribution shortcode yet so we should be fine.

My one request from a UX perspective is that: right now, if you click on a contribution from the "contributions dashboard" all it does is copy the shortcode. With the proposed change, we will allow them to edit it.
We need to be sure that, if it is an old shortcode, that we keep the current behavior so that it is apparent that they cannot edit those. Let me know if you have any questions!

**Comment by ksmoore125** [comment]
[Moved to Jira](https://laterpay.atlassian.net/browse/CLIENTS-654)
