### ISSUE TITLE
Update Paywall Preview to match Paywall

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#152]
# Description
We received quite a bit of feedback during our user testing session that it would be nice if the Paywall Preview matched the actual paywall.
This was done intentionally because we were going to switch the implementation to use "LaterPay OnPage" thereby making them match. However, we will no longer be using "LaterPay OnPage" so we should move forward with this change.

# Acceptance Criteria
- Make the Paywall Preview match the Paywall
- **EXCEPTIONS:**
  - Leave the Dynamic Pricing ⭐   indicator in the preview
  - Don't show the purchase button or the 'I already bought this' link in the preview
  - Don't show the radio buttons in the preview

Paywall Preview | Paywall
-- | --
![image](https://user-images.githubusercontent.com/41650164/83451264-3dbc1f80-a41c-11ea-8e79-a6c9de24f010.png) | ![image](https://user-images.githubusercontent.com/41650164/83451176-2d0ba980-a41c-11ea-9ef2-bcdca0f2ea57.png) 

**NOTE:** Let @ksmoore125 know if design specs would be helpful and we can provide those

**Comment by milindmore22** [comment]
@ksmoore125 just to clarify should I follow the same font and font size as on Paywall?

**Comment by ksmoore125** [comment]
Yes please, we want them to look as close to the same as possible.
