### ISSUE TITLE
"Already bought this" link not working

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#159]
**Steps to Reproduce**
- Publish a Paywall
- View on Live Post
- At the bottom of the Paywall, click "I already bought this" below the purchase button

**Observed Result**
![image](https://user-images.githubusercontent.com/41650164/83798160-6dac3280-a669-11ea-8259-9cbcbc6ba539.png)

**Desired Result**
It should take you to the LaterPay login screen [as is done here](http://lpwptestprod.wpengine.com/2019/07/09/hello-world/)

**Comment by milindmore22** [comment]
@ksmoore125 Unable to reproduce the issue, can you please let me know steps in detail
Also please confirm this is not related to the connector.

**Comment by ksmoore125** [comment]
I am [checking with the LaterPay team here](https://laterpay.slack.com/archives/C02JCERA4/p1591730816001500).

**Detailed Steps to Reproduce**
- Open [this link](http://kimberlystestsite.cloudaccess.host/2020/03/newest-post-960-words/) in an incognito window
- At the bottom of the Paywall, click "I already bought this" below the purchase button

**Comment by milindmore22** [comment]
Updating code to delete purchase options data when the plugin is deleted as per discussion [here](https://rtcamp.slack.com/archives/C02JCERA4/p1592247830005800)
