### ISSUE TITLE
Add Settings Tab

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#16]
# User Story
As a LaterPay merchant, I would like to be able to edit my settings after their initial configuration.

# Acceptance Criteria
- Add a Settings page where the merchant can modify
  - The number of articles posted per month (#4 )
  - Their merchant ID & API key 
    - These should be verified when they are updated
  - ~~Free access for specific user roles~~ _Removed from scope_
  - Configure their GA information so that we send events to them as well (similar to what we do in the existing plugin)

# Mockup
[Prototype](https://xd.adobe.com/view/a9c3cfb2-0efc-4d74-b792-3383ce0918fa-fc90/?fullscreen) | [Design Specs](https://xd.adobe.com/view/a9c3cfb2-0efc-4d74-b792-3383ce0918fa-fc90/) _To view the detailed design spec's click the `</>` icon in the righthand menu and click around the mockup for details on each element_

![image](https://user-images.githubusercontent.com/41650164/79503817-6bc5db80-7ff7-11ea-9da8-5effa533db0b.png)

# Additional Resources
### Google Analytics Tooltip Copy
> **Your Google Analytics**
Provide us with your [Google Analytics UA-ID](https://support.google.com/analytics/answer/7372977?hl=en) and check to enable this feature if you would like to receive LaterPay events in your own Google Analytics instance.
> 
> This will include things like the number of times your customers come across our paywall as well as the number of successful purchases, so that you can easily track your conversion rates.
> 
> For more analytics, log in to your [LaterPay Merchant Portal](https://www.laterpay.net/) and check out your Analytics Dashboard.

### LaterPay Google Analytics Tooltip Copy
> **LaterPay Google Analytics** 
LaterPay collects information on how you are using our plugin in order to improve our products and services. We are not in the business of selling data but use this data only to benefit you, our customer. 
> 
> If you would like more information, contact wordpress@laterpay.net.

**Comment by milindmore22** [comment]
Hello @ksmoore125
After checking mockups, I found we don't have a submit button for updating settings, can you please confirm if we are going to update the field value as merchant changes them or use a Submit button to save all at once, I have used the first way ( i.e on change ), if a button to save all is needed please let me know.

**Comment by ksmoore125** [comment]
@milindmore22 - Updating on change is nice; it is a better UX, we just need to be able to validate the API credentials. As long as we have a way to do that, then no change is needed.

**Comment by ksmoore125** [comment]
Changes to this are on hold until the Contributions items are complete.

**Comment by ksmoore125** [comment]
@milindmore22 - I would actually like to save this for a future version of the plugin. Would it be simple to hide this from the sidebar so we can save it for later?

If it is not simple to hide this for now, let me know and I will provide feedback so that we can go ahead and release this with the initial version.

**Comment by milindmore22** [comment]
@ksmoore125 Yes, we can hide this one for now. I will update code.

**Comment by ksmoore125** [comment]
When we pick this back up, we did get feedback in our user testing session that:
> Once Merchant inserts the Merchant ID and API Key in the Account tab, there is no "Save" button nor instructions on how to save it.

**Comment by milindmore22** [comment]
@ksmoore125 As per the previous comment should I proceed with the Save button, Also the save button will be for all the form fields right? not just for Merchant ID and API key, Also what should be instructions for the Merchant ID and Key fields

![image](https://user-images.githubusercontent.com/1132541/85418588-95b6f380-b58e-11ea-85cc-4ccf544ee792.png)

**Comment by ksmoore125** [comment]
Yes, let's have one save button at the bottom (as shown and which is consistent with the main WordPress Settings page). This should save all fields.

Can we also have a warning message if the merchant makes a change and then tries to leave the page without saving?
> **You have unsaved changes.**
> Are you sure you want to leave this page without saving?
> `Leave & Discard Changes` `Stay`

_Where `Stay` is the active button_

**Comment by milindmore22** [comment]
Unfortunately, most of modern-day browsers will not provide the ability to add custom messages or buttons to [prevent scamming and losing data ](https://bugs.chromium.org/p/chromium/issues/detail?id=587940)
Since we are using browser event ( [onbeforeunload](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload) ) we are unable to add custom popup, we will have to go with default browser messages. like
Chrome 
![image](https://user-images.githubusercontent.com/1132541/85546462-8beaca00-b63a-11ea-8516-e00562a33408.png)
Firefox
![image](https://user-images.githubusercontent.com/1132541/85546780-e08e4500-b63a-11ea-9ac5-e59431929d67.png)
Opera
![image](https://user-images.githubusercontent.com/1132541/85546824-ec7a0700-b63a-11ea-8493-090b23dd3a2f.png)
Safari
![image](https://user-images.githubusercontent.com/1132541/85546930-061b4e80-b63b-11ea-8de2-dee88df258b4.png)

**Comment by ksmoore125** [comment]
We can use the default browser message; thanks for the clarification!

**Comment by ksmoore125** [comment]
**Product check notes:**
- Please decrease the spacing between `Merchant ID` and `API Key` to show that these are grouped together (as shown in the [design specs](https://xd.adobe.com/view/a9c3cfb2-0efc-4d74-b792-3383ce0918fa-fc90/screen/870f8a22-0bf8-44b3-97e3-4cc60205d94d/3-Settings))
- Similarly, please decrease the spacing between the two GA sections
- Please have LaterPay GA Enabled checked by default
- Please update the `Analytics` & `Google Analytics “UA-ID”` headers so that the font matches the design specs (see CSS below)

```text-align: left;
font: Regular 16px/18px Helvetica Neue;
letter-spacing: 0px;
color: #1D1D1D;
opacity: 1;

**Comment by milindmore22** [comment]
> Please have LaterPay GA Enabled checked by default

According to plugin [guidelines](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#7-plugins-may-not-track-users-without-their-consent), we should not track users without their consent.

We should add a possible Welcome Screen / Popup to asking for user consent.

eg: WooCommerce
![image](https://user-images.githubusercontent.com/1132541/85665691-3e716a00-b6d9-11ea-8cca-ab46390a520a.png)

or
![image](https://user-images.githubusercontent.com/1132541/85665824-5fd25600-b6d9-11ea-98f0-5e3585370e76.png)

**Comment by ksmoore125** [comment]
I have requested input from our design team ([here](https://laterpay.slack.com/archives/C03CR9361/p1593094378002600) for my future reference). I will let you know as soon as I hear back from them.

**Comment by ksmoore125** [comment]
@milindmore22 - The settings page looks good but for some reason I am no longer able to connect my account to LaterPay.

**Steps to Reproduce**
_Let me know if this issue is unrelated and if so, I will create a separate ticket for it._

- Create a fresh install of the plugin
- On the welcome screen, select Paywall
- Select more than 10 posts
- Skip Tutorial
- Click Publish, then connect
- Enter your API credentials

**Observed Result**
The spinner continues spinning and the account does not connect

**Notes**
You can reproduce this [here](http://kimberlystestsite.cloudaccess.host/wp-admin/admin.php?page=revenue-generator-paywall) using the credentials shared[ here.](https://rtcamp.slack.com/archives/GA2P84GBZ/p1591877938000600?thread_ts=1591808197.000400)

**Comment by milindmore22** [comment]
There seems to be a conflict between merchant verification code, it will be resolved in the same PR no need to create a separate ticket for it.

**Comment by ksmoore125** [comment]
@milindmore22 - [Here is the design](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5ef9feda4156b413529e972a) for the tracking consent checkbox

**Comment by ksmoore125** [comment]
@milindmore22 - This looks good. Please let me know if you would like me to create a separate ticket for the tracking consent checkbox (above) or if that can be addressed in this ticket.
