### ISSUE TITLE
Buying one single article appears to give access to the entire site

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#160]
**Steps to Reproduce**
- Configure a Paywall that applies to "all posts and pages" 📝 
- Publish and view on a page
- Purchase the article 
- Note that you can access the article ✅ 
- Navigate to another article

📝  I recommend setting the single article to PayLater and with a price below 0.10 since with PayLater, no payment is required. Additionally, if you open the site in an incognito window you will also essentially clear your tab so that you can test over and over.

**Observed Result**
You can also access all other articles on the site

**Expected Result**
The `Individual Article` purchase option should only purchase the ONE article (even if it is on a paywall which applies to multiple articles).

This same issue applies `category` and `except for category`  as well.

**Comment by milindmore22** [comment]
@ksmoore125 I am unable to reproduce this issue.

**Comment by ksmoore125** [comment]
**Alternative Steps to Reproduce**
- [Open this link](http://kimberlystestsite.cloudaccess.host/2020/03/newest-post-960-words/) in an incognito window
- Purchase the individual article ($0.49) 
- [Navigate to this article](http://kimberlystestsite.cloudaccess.host/2020/03/newest-post/)

**Observed Result**
You are able to access that article even though it should have a paywall on it

**Details**
As mentioned in the ticket, purchasing a time pass or subscription should give access to all articles that the paywall "applies to" (in this case all posts & pages).
BUT the individual article option should always only provide access to the one item/article that was purchased (in this case `newest-post-960-words`)

**Comment by milindmore22** [comment]
@ksmoore125 

There seem to be conflicts with a deleted purchase option, Updated code to exclude deleted purchase options from connector JSON 
eg: If Subscription is valid for 1 month and it is deleted, it will be valid for another 1 month from the date of deletion, so we should exclude it post-expiration date.

Excluding expired options Also seem to fix #159 Creating a long URL which includes all the time passes and subscriptions, creating a long link.
