### ISSUE TITLE
Update Paywall Prioritization now that Multiple Items can be Selected

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#18]
# User Story
As a LaterPay Merchant I want to be 100% confident as to which Paywall will appear on which article so that I have insight into my business.

# Acceptance Criteria
- Ensure that the correct (most specific or most recent) paywall is what is displayed on an article
- Ensure that the Priority sort order on the Dashboard (#38 ) is updated accordingly 

### Details
The new prioritization should be order by
- Most Specific
- Most Recent

Where `Most Specific` is defined as:
1. One Article
2. A group of articles
  - If an article applies to more than one in this group, the fewer the number of articles, the higher the priority
3. One category
4. A group of categories
  - If an article applies to more than one in this group, the fewer the number of categories, the higher the priority
5. All posts & pages

If there is a tie in any of these, the more recent should take priority.

Relates to: https://github.com/laterpay/revenue-generator/issues/7, https://github.com/laterpay/revenue-generator/issues/20, https://github.com/laterpay/revenue-generator/issues/14

**Comment by ksmoore125** [comment]
**Product Check Notes:**
Below is a list of priorities checked:

Priority Rank | Applies to | One selected | Multiple Selected
-- | -- | -- | --
1 | this page only | ✅  | --
2 | specific posts / pages | ✅  | ⚠️
3 | category | ✅  | ⚠️
4 | except for category | :hammer_and_wrench: | :no_entry:
5 | all posts | :hammer_and_wrench: | -- 
6 | all posts & pages | ✅  | -- 

The priority order on the Paywall Dashboard was correct ✅ 

## ⚠️ Multiple Categories or Posts should be a lower priority than on category
_The below example is for categories but the same applies for specific posts / pages. A paywall with fewer posts/pages selected is more specific than one with more posts/pages and therefore the paywall with fewer should take higher priority._

**Steps to Reproduce**
- Create & publish a paywall that applies to 1 category
- Create & publish a second paywall that applies to the above category + one more
![image](https://user-images.githubusercontent.com/41650164/90051208-f6180680-dc9c-11ea-86cf-70aa801d884f.png)

**Actual Result**
The more recent paywall is displayed
![image](https://user-images.githubusercontent.com/41650164/90051262-09c36d00-dc9d-11ea-8adc-61b7171fa4ca.png)

**Expected Result**
The "more specific" should be applied

_Within each "priority rank", the few items selected, the higher the priority. 
For example, if I have category `A` `B` and `C`, and I set:
-  `Paywall A` to apply to category `A`
- `Paywall AB` to apply to category `A` and `B` then 
- `Paywall BC` to apply to category `B` and `C` and a final 
- `Paywall ABC` to apply to all 3 categories 
then the priority should be as follows:_

Priority Rank | Paywall Name | Notes
-- | -- | --
1 | Paywall A | This is the most specific since it only applies to 1 category
2 | Paywall BC | This is tied with Paywall AB but since it is newer, it will take priority
3 | Paywall AB | _see above_
4 | Paywall ABC | This is the lowest priority since it is the least specific (since it applied to the highest number of categories)


## :hammer_and_wrench: "View on live post" opened post with a different paywall
After creating a paywall which applied and clicking "Publish" -> "View on live post" it opened a post with a different paywall displayed on it. This happen for both "all posts" and "except for category." The others appeared to work as expected and the paywall prioritization appeared to work properly as well.

## :no_entry: Except for categories should be "or" and does not appear to be working
**Steps to Reproduce**
- Create `Paywall 1` which applies to "except for categories" `A` `B` `C`
- Select a post (`Post A`) in category `A`
- Select a post (`Post ABC`) which is in all of the categories `A` `B` & `C`

**Observed Result**
`Paywall 1` is displayed on `Post A` and also `Post ABC`

**Expected Result**
Since both of these posts contain at least 1 of the "except for categories" `Paywall 1` should not appear on these posts

**Comment by milindmore22** [comment]
> 🛠️ "View on live post" opened post with a different paywall

Regarding `all posts`, It will open the latest post type `post`, we can not determine if `preview post` has no `another paywall applied` if we are `dynamically choosing preview post`, Also if we add code to search for `another paywall` until current paywall has priority ( All Posts ) it might end up in a never-ending loop.

Another Paywall: Category, Individual, Except Category.
Current Paywall: All Posts.

**Comment by ksmoore125** [comment]
@milindmore22 - It appears that the issue above with title "⛔  Except for categories should be "or" and does not appear to be working" has not yet been resolved. The others look good though! Please let me know if you have any doubts.

**Comment by milindmore22** [comment]
@ksmoore125 
I am unable to reproduce ***Except for categories should be "or"*** on my local and test site, however, I noticed that it was not redirecting to correct Preview page for excluded categories, which is a small fix [c42beda](https://github.com/laterpay/revenue-generator/commit/c42bedacc1b0a1f63e162b990d1d0e11a05d4375), 
can you please let me know steps to reproduce it.
eg: **Post A** has **Cat A** http://kimberlystestsite.cloudaccess.host/2020/09/post-a/
eg: **Post ABC** has **Cat A, B & C** http://kimberlystestsite.cloudaccess.host/2020/09/post-abc/

**Comment by ksmoore125** [comment]
@milindmore22 - Here is the simplest case:

1. Create a paywall set to `except for category` and choose one category (ie: `CatA`)
2. Publish paywall
3. Navigate to a Post that is in `CatA`

**Observed Result** 
You see the paywall

**Desired Result**
The paywall should not be displayed on any post in `CatA`

**Example:**
[This post](http://kimberlystestsite.cloudaccess.host/2019/03/sample-post-3/) is in the `Sport (Free)` Category

Paywall | Post
-- | --
![image](https://user-images.githubusercontent.com/41650164/91891112-114fb380-ec56-11ea-98bb-853359123c43.png) | ![image](https://user-images.githubusercontent.com/41650164/91891142-1ad91b80-ec56-11ea-84b0-c00fe91e462f.png)
