### ISSUE TITLE
Subscription & Time Pass Functionality Update

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#19]
# Summary
In v1 of the plugin all Subscriptions and Time Passes must apply to the entire site. This was to reduce the complexy & address the most common use case. However, we do need to provide the ability for merchants to apply a time pass or subscription to only one specific paywall.

# Acceptance Criteria
- Remove ` (for the entire site)` from the end of the Time Pass and Subscription Purchase options
- Add a toggle to the Time Pass and Subscription Purchase more options menu
  - `Site-wide` v `Paywall Specific`
  - Site-wide should be selected by default
  - Ensure that the implementation include the functionality details & tooltip copy below

## Functionality
**Site-wide Time Passes & Subscriptions**
- Displayed on all paywalls
- Changes made while editing one paywall will be reflected on all paywalls
- Provide access to the entire site
- Any changes should trigger the existing warning message ([shown here](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e4deac2497bf47c22d456e0); see https://github.com/laterpay/revenue-generator/issues/164 for additional details)

**Paywall Specific Time Passes & Subscriptions**
- Displayed only on this specific paywall
- Changes only affect this specific paywall
- Purchase only provides access to content which falls under the `applies to` selection for this specific paywall
- Changing the `Site-wide v Paywall Specific` toggle should trigger the existing warning message ([shown here](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e4deac2497bf47c22d456e0); see https://github.com/laterpay/revenue-generator/issues/164 for additional details)

## Tooltip Copy

> **Site-wide v Paywall-specific 
> Time Passes and Subscriptions**
> 
> A site-wide time pass or subscription is common across all paywalls and provides access to your entire site.
> 
> A paywall-specific time pass or subscription will only be applied to this paywall and will only provide access to the content selected at the bottom of this page.

**Comment by ksmoore125** [comment]
We will hold off on this and see if it is requested

**Comment by milindmore22** [comment]
@ksmoore125 
I have few doubts about this functionality I want to clear before I start working on it 
how will this affect for "all posts" and "all posts and pages" in terms of specific Time Passes and Subscriptions?
are we removing those options for specific purchase options or we change specific purchase options to sitewide if all posts or all posts and pages are selected

**Comment by ksmoore125** [comment]
@milindmore22 - Good catch; thanks for asking! Let's do the following:

- Update the default "applies to" selection so that it is set to `this post only` (let me know if you would like a separate ticket for this)
- Disable the toggle for "all posts and pages" so that it requires `Site-wide`
  - Use the same behavior we currently have for the `Pay Now` pricing (shown below) so that if they change the "applies to" to "all posts and pages" then we display a warning message (below), expand the more options menu & show the toggle as changed.

> Your Time Passes & Subscriptions will now be site-wide.

Example behavior:
![Screen Shot 2020-08-17 at 9 44 04 AM](https://user-images.githubusercontent.com/41650164/90408992-36490180-e06e-11ea-9cf8-43d512f084b5.png)

Please let me know if you have any additional doubts or if a prototype would be helpful. Thanks again!

**Comment by ksmoore125** [comment]
@milindmore22 - After sleeping on it, please disregard my comment above; I will delete it so as not to cause confusion in the future.

The `Site-wide` functionality means that the subscription/time pass shows up on every paywall & changes to the sub/tp made in one place are reflected across all paywalls (like it does today)

The `Paywall-specific` functionality means that the subscription/time pass is displayed and managed on this paywall only.

Therefore let's say that we have 2 paywalls: `All posts & pages` & `In News Category`
_If I set up a `site-wide` subscription (for either paywall):_
- That subscription gives access to the whole site
- That subscription shows up on both paywalls
- Any change to that subscription on one paywall edit screen is made in both places

_If I set up a `paywall-specific` subscription:_
- That subscription is displayed & provides access to any post/page any where that paywall is displayed
  - For `In News Category` that means that the subscription will give access to the "News" category and show up on that paywall
  - For `All posts & pages` that means that the subscription will give access to anything not in the "News" category (since this paywall would not be displayed there)



> I am guessing this is difficult to set up so please let me know if you have any doubts, suggestions, etc.
> cc: @tomasstark

**Comment by milindmore22** [comment]
@ksmoore125 

> For All posts & pages that means that the subscription will give access to anything not in the "News" category (since this paywall would not be displayed there)

One More confusion about All Posts and Page

Assume a user creates paywall Applied to "all posts and Pages" and adds a subscription which is paywall specific, along with Sitewide subscription check screenshot ( Screenshot )

Assuming The Paywall is Applied to "All Post and Page"

- What should happen if the user purchases a "sitewide" Subscription?
- What should happen if a user purchases a "paywall specific" subscription?

![image](https://user-images.githubusercontent.com/1132541/92123966-d2b72600-ee1a-11ea-806e-e7b89e57bb43.png)

**Comment by ksmoore125** [comment]
Let's use this as an example:
We will pretend we have a site with 3 posts:
- Post 1 -> In Category A
- Post 2
- Post 3

We also have the following 2 paywalls set up:
- `Paywall A` -> Applies to Posts in Category A aka Post 1
- `Default Paywall` -> Applies to all posts and pages (aka everything except Post 1)

## Scenarios:

User Purchase | Access Post 1? | Access Post 2&3?
-- | -- | -- | --
Paywall specific subscription on `Paywall A` | ✅  | ❌ 
Site-wide subscription (displayed on both `Paywall A` & `Default Paywall` | ✅  | ✅  
Paywall specific subscription on `Default Paywall` | ❌  | ✅ 

_This is because the subscription grants them access to the content that is hidden behind the paywall that they purchase. Even though the Paywall specific subscription on `Default Paywall` applies to all posts and pages, that subscription offer will not be displayed on Post 1 and therefore should not grant access to Post 1._

**Comment by ksmoore125** [comment]
@milindmore22 - After speaking with the team here, we are actually going to hold off on this until we can get feedback from merchants on this behavior. I will close the ticket for now.
