### ISSUE TITLE
Allow for Selection of Multiple Single Articles

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#20]
# User Story
As a LaterPay merchant, I would like to specify that a paywall can apply to one **or more** single articles.

# Acceptance Criteria
* Allow a merchant to select multiple URLs under the `specific posts or pages` selection ([shown here](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e5d4b554085d175a85a8aed))

Relates to: https://github.com/laterpay/revenue-generator/issues/7, https://github.com/laterpay/revenue-generator/issues/14, https://github.com/laterpay/revenue-generator/issues/18, https://github.com/laterpay/revenue-generator/issues/25

**Comment by milindmore22** [comment]
@ksmoore125 Sorry forgot to ask you this on Friday
how are we planning to handle multiple post/page selection on footer bar
![image](https://user-images.githubusercontent.com/1132541/88509083-f1e1bd00-cffd-11ea-818a-3cc7383ff4f0.png)

**Comment by ksmoore125** [comment]
Our designer is out today so, could we do something like this (but using the standard fonts etc):

![image](https://user-images.githubusercontent.com/41650164/88542156-9b638700-cfdb-11ea-9d0d-7aa82d1c4b24.png)

**Comment by milindmore22** [comment]
@ksmoore125 
[select2](https://select2.org/) Do not provide this solution, I will look for a custom solution, the rest of coding is done
one more question, how are we planning to handle multiple paywalls assigned on a post, which one should be prioritized and displayed

**Comment by ksmoore125** [comment]
@milindmore22 - The prioritization is outlined in https://github.com/laterpay/revenue-generator/issues/18. Please let me know if you have doubts!

**Comment by ksmoore125** [comment]
**Product Check Notes:** Everything looks and works great! The only thing is that the paywall dashboard should be sorted in priority order, with the highest, priority on top. Therefore `specific posts & pages` should be towards the top (with `this page only` being the only more specific aka higher priority option)
