### ISSUE TITLE
Do not Expand Paywall Name Text Box

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#200]
**Steps to Reproduce**
- Create a new Paywall
- Click to edit the paywall name and the bottom of the screen (ie: “Paywall1”)
- Type a Paywall Name longer than 20 chars

**Observed Result:**
The bottom bar UI breaks, and the main call to actions gets stacked vertically. 
[See video here](https://laterpay.slack.com/archives/C02JCERA4/p1592237782000700?thread_ts=1592237768.000400&cid=C02JCERA4)

**Desired Result:**
Set the maximum length for Paywall Name to 20 chars ~~and ellipse the rest (= use “…” ).~~
<img width="863" alt="Screen Shot 2020-06-11 at 18 07 35" src="https://user-images.githubusercontent.com/41650164/84681226-70c0e180-aef9-11ea-8930-2d1e4e864211.png">

**Comment by milindmore22** [comment]
@ksmoore125 Currently we have fix input width with text inside scrolling horizontally, adding ellipsis might affect the design and we will end up seeing white space, Video Shared in Slack

**Comment by ksmoore125** [comment]
@milindmore22 - I have removed the requirement to add the ellipsis

**Comment by ksmoore125** [comment]
## Comments
I copied the ticket description from feedback provided by our design team. Although the ticket says to limit the name to 20 characters, I think that we don't need to limit the characters (for this reason), we just need to ensure that the UI does not break [as is is shown in the video here](https://laterpay.slack.com/archives/C02JCERA4/p1592237782000700?thread_ts=1592237768.000400&cid=C02JCERA4).

However, while testing I did find the following two issues. If we remove the field limit and just address the UI then you may disregard "Item 2"

## Item 1
**Steps to Reproduce**
- Create a new paywall
- Scroll down to the paywall name (let's say it is defaulted to `Paywall 1`)
- Type a longer name in the Paywall field (ie: `Paywall 123456789012`)

**Observed Result**
When you click away, what is shown in the Paywall field is `23456789012`
- You cannot use the cursor to select the text and move it to the beginning of the name
- You cannot use the arrow keys on the keyboard to show the beginning of the name
This is a bit surprising and frustrating.

**Desired Result**
- When you click away, it should show the first part of the Paywall name (ie: `Paywall 123`)
- You should be able to use your cursor or the arrow keys to navigate back and forth within the field

## Item 2
The field limitation is not applied on the product dashboard
![image](https://user-images.githubusercontent.com/41650164/87078044-b2d3ff00-c1e9-11ea-8e2c-0f5c5862321f.png)

**Comment by ksmoore125** [comment]
We still need to resolve `Item 2` above. We need to limit to 20 characters on the Paywall dashboard as well.
