### ISSUE TITLE
Paywall Tutorial: Search Icon Greyed Out

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#207]
**Steps to Reproduce**
- Start the Paywall Tutorial

**Observed Result**
The article search icon is greyed out at the beginning of the tutorial
![image](https://user-images.githubusercontent.com/41650164/84916601-e2c53200-b083-11ea-801a-db2c653f30a6.png)

When you get to the final steps (I believe it starts with step 7) the category search field appears and the search icon is greyed out
![Screen Shot 2020-06-17 at 10 11 56 AM](https://user-images.githubusercontent.com/41650164/84916343-9548c500-b083-11ea-9dd1-22dfa8ca6d3a.png)

**Desired Result**
The search icon background should be white

**Comment by milindmore22** [comment]
Unable to reproduce this issue.

![image](https://user-images.githubusercontent.com/1132541/85142034-6427ea80-b265-11ea-99f3-d7ce1ef10fb4.png)

![image](https://user-images.githubusercontent.com/1132541/85142148-89b4f400-b265-11ea-85e4-05718365f40e.png)

**Comment by ksmoore125** [comment]
Unable to reproduce
