### ISSUE TITLE
Update Revenue Generator Readme

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#226]
# Acceptance Criteria
- Update https://wordpress.org/plugins/revenue-generator/ so that it includes more references to paywalls since this is our core feature. 
  - [Recommended updates can be found here](https://docs.google.com/document/d/18qrOaGIIca8YJqERH_fD1CS2wOJ6ceqN9XygERpssFQ/edit?ts=5e8ad753).
- Update the images as follows

Order | Description | Image
-- | -- | --
0 | The Revenue Generator leverages LaterPay's extensive experience in the publishing industry to help you create Paywalls and Contributions with a near-frictionless user experience. |  [Image here](https://drive.google.com/file/d/1wmZcsVV6H8U6LXL7sQkiVExKBuVJ8m0d/view)
1 | The Revenue Generator onboarding walkthrough guides you through the process to ensure that your initial setup is as smooth as possible. | [Image here](https://drive.google.com/file/d/1j6OIlULndVdBz7UWHY3D6LiQ7-kvsjXy/view)
2 | Use our in-line editor to configure your paywall while previewing it on an article so that you know exactly what your followers will see. | [Image here](https://drive.google.com/file/d/1KHte-jZUdhy6zE0c1J6vDY6wFKVGvbA3/view)
3 | LaterPay's Revenue Generator takes the guesswork out of pricing your content by setting default recommended prices based on your user base and providing Dynamic Pricing for individual article prices. | [Image here](https://drive.google.com/file/d/1_dWrqilbFNZM7HwjMdNWhB6QPxG_MYHR/view)
4 | On the Paywall Dashboard, you can view all your paywalls in one place to easily manage your site. | [Image here](https://drive.google.com/file/d/1y14Iss1ZCWne6zGpVgwNR89q872HtDaB/view)
5 | Once you've configured your paywall and clicked "Publish," it is seamlessly applied to your site. | [Image here](https://drive.google.com/file/d/1KkyXbFsAL5q6i4_OdAZLcAnTAS2nEnS_/view)
6 | With the Revenue Generator, you can also easily request contributions from your followers. | [Image here](https://drive.google.com/file/d/1IruR3xrZIKxO2PML8J4JWgnondz0AVJP/view)
7 | Simply copy and paste the contributions shortcode onto your site for a frictionless contribution experience. | [Image here](https://drive.google.com/file/d/1udXoEUV6OL9917cgk1xZGeS1ursiwbnB/view)

**Comment by ksmoore125** [comment]
@milindmore22 - I took a look and the text changes do not appear to be reflected. The [recommended updates are shown here in hot pink text](https://docs.google.com/document/d/18qrOaGIIca8YJqERH_fD1CS2wOJ6ceqN9XygERpssFQ/edit?ts=5e8ad753). Let me know if you can't see them.

**Comment by milindmore22** [comment]
@ksmoore125 I am not able to see text change

**Comment by milindmore22** [comment]
@ksmoore125 can you please verify text changes in the readme.
https://github.com/laterpay/revenue-generator/pull/236/files

**Comment by ksmoore125** [comment]
@milindmore22 - Those changes look great, thanks!
