### ISSUE TITLE
LaterPay Google Analytics Not Enabled

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#231]
**Steps to Reproduce**
- Install a new version of the plugin
- Navigate to the Revenue Generator Welcome screen and note that the box to enable analytics is checked
- Proceed to the next screen (thereby agreeing to allow analytics)
...
- Navigate to the Settings page

**Observed Result**
`LaterPay Google Analytics` is not enabled
![image](https://user-images.githubusercontent.com/41650164/87813375-6c088980-c827-11ea-985f-fb7f4e388d75.png)

**Desired Result**
This should be enabled (and the corresponding box checked) unless it is disabled here or on the Welcome Screen

**Additional Item**
How will this behave for anyone who as installed v1.0.0? It would be nice if it was checked by default.

**Comment by milindmore22** [comment]
I have added default checked for already installed plugin
