### ISSUE TITLE
Update LaterPay Logo

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#238]
## Description
LaterPay has recently gone through a rebranding effort and has updated their logo. Therefore, we need to update our logo in all locations including the following:

## Acceptance Criteria
- Update "LaterPay" to "Laterpay"
  - Ensure this change is made throughout the plugin and on the plugin page
- Update the LaterPay logo in all locations including the following:
  - ⭐  - [See branding assets here](https://drive.google.com/drive/folders/14qLhWiAp_qgi_VtrUBgq9EFpRp8P7vgQ)

Description | Screenshot | New Logo
-- | -- | --
WordPress sidebar | ![image](https://user-images.githubusercontent.com/41650164/89923796-bb439f00-dbc6-11ea-953a-5e2ad91c575c.png) | ⭐ 
Paywall button | ![image](https://user-images.githubusercontent.com/41650164/89923954-ea5a1080-dbc6-11ea-88f8-59e91a45e248.png) | ⭐ 
"Powered by LaterPay" below the paywall | _see image above_ | ⭐ 
"Powered by LaterPay" in the paywall preview | ![image](https://user-images.githubusercontent.com/41650164/89924440-a0bdf580-dbc7-11ea-8b1b-1e869569a5b1.png) | ⭐ 
"Powered by LaterPay" in the contribution widget | ![image](https://user-images.githubusercontent.com/41650164/89924878-3c4f6600-dbc8-11ea-9346-a50230e41a87.png) | ⭐ 
Waiting image | ![image](https://user-images.githubusercontent.com/41650164/89924303-74a27480-dbc7-11ea-8b3d-0b342de14daf.png) | Use the same loading circle that is used elsewhere in the plugin (here [1](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c10c4034abf8d20317088), [2](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c10c4292e3b8b99f1428a), [3](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c10c4cf17278c82b2d6e6))
WordPress plugin page logo | ![image](https://user-images.githubusercontent.com/41650164/89925486-1c6c7200-dbc9-11ea-9bc0-86c78d34da52.png) | [Here](https://drive.google.com/file/d/1fvke_c4jJWOAaGI1gME_VWkXZ26qfIBU/view)
WordPress plugin page banner image | _see image above_ | [Here](https://drive.google.com/file/d/1j66-3NUHJADpPYgji2NVMH0wBj9llk1N/view)

**Comment by tomasstark** [comment]
@ksmoore125 The following items come from Connector script directly:

- Paywall button
- "Powered by LaterPay" below the paywall

For that reason, we can't change up those assets and it needs to be updated in the connector directly.
