### ISSUE TITLE
Allow for Paywall to Apply to all Posts

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#25]
**Acceptance Criteria**
Update the Applies to dropdown so that it includes the following (`new functionality highlighted`) **in the following order**:
- all posts and pages
- `all posts`
- category
- except for category
- `specific posts or pages` (see #20 )
- this post (or page) only

**Comment by ksmoore125** [comment]
Will handle in separate tickets.

**Comment by milindmore22** [comment]
We will cover `specific posts or pages` in ticket #20

**Comment by ksmoore125** [comment]
Overall this looks good; the only issue is that when I selected apply to `all posts` and then to `view on live post` I was taken to a page which did not have the paywall on it. Instead I should have been taken to a post which did have the paywall on it.
