### ISSUE TITLE
Investigate the possibility of loading post images and CSS in Paywall preview

### ISSUE THREAD

**Issue by tomasstark** [laterpay/revenue-generator#281]
## Final Outcome

Determine if it is possible for the Revenue Generator Preview to also load Images & CSS and if so, what the effort would be. Also provide some outline of the ideal approach for implementing this.

## Description

In order to make sure that the merchant will know what their site will actually look like with our paywall on it, we need to be able to pull in their images &/or CSS when we show them the article preview in the Revenue Generator (when editing paywall on **Revenue Generator → Paywall** screen).

The discovery is complete when:

- We know if this is possible (given all the different WP themes, etc)
- We have a rough effort estimate
- We have approximate steps for implementation outlined

**Comment by milindmore22** [comment]
I would recommend creating a [template file](https://developer.wordpress.org/themes/template-files-section/post-template-files/#single-php) which can be loaded for only previews, a single page template without header and footer, 
PS: I would not recommend pulling the theme's CSS and JS in the backend for preview, this might affect overall backend working by creating JS conflicts, and overwriting backend CSS with frontend might create styling issues.

**Comment by tomasstark** [comment]
Thank you @milindmore22!
