### ISSUE TITLE
Paywall Configuration

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#3]
# User Story
As an Easy Paywall merchant, I would like to be able to customize the text and options available on my paywall so that I can ensure that it provides an exceptional experience to my specific user group.

# Acceptance Criteria
1. ~Merchant should be able to edit the paywall heading 
[View here](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=12%3A471)~

2. ~Merchant should be able to edit the paywall description 
_Not shown in prototype but should function similarly to the header_~

3. Merchant should be able to remove the paywall (making the selected content free)
[View here](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=12%3A16374&scaling=scale-down-width)
   - When the merchant chooses to delete, we should request that they confirm.
[View here](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=17%3A4875&scaling=scale-down-width)
   - When the paywall has been removed, we should replace the content selection bar at the bottom of the page with a bar allowing them to add a paywall
[View here](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=17%3A5197&scaling=scale-down-width)

### Default values:
**Paywall Heading**
Keep Reading

**Paywall Description**
Support {site url} to get access to this content and more.

**Design Specs**
[Paywall Hover](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c1e36ffef6f0b387fd05c)
[Confirm Deletion](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c011712c0bb09aed65eba)
[Add a new Paywall](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c0117723c51b36440143e)

**Comment by ksmoore125** [comment]
@thrijith - I have spoken to the LaterPay team and in the first version of LaterPay OnPage, the merchant will not be able to customize the paywall header or description so I have removed that from scope. I am sorry for the extra work. 
We do plan to add this functionality in the future though.

**Comment by thrijith** [comment]
@ksmoore125 Removed option to edit Paywall Header and Description.

**Comment by ksmoore125** [comment]
One minor change: Could this footer also stay at the bottom of the page without needing to scroll like the content selection footer?
