### ISSUE TITLE
(5) Purchase Option: Reorder Options

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#33]
### Sub Task of #5 

# User Story
As a Laterpay merchant, I would like to be able to customize the order of the purchase options so that they make sense to my customers and also so that I can highlight the most desired option.

# Acceptance Criteria
When a merchant hovers over an individual purchase option, they should be able to:
- Move the option up or down one item at a time using the up or down arrows
[Demo here](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=68%3A5284&scaling=scale-down-width) by clicking the down arrow on the first option
  - [First (top) option](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c064c90bcf1b344ca9439) should not show the up arrow 
  - [Last (bottom) option](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c064df5c4a90cf7c18546) should not show the down arrow
  - [Middle option(s)](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c064d85ff6695dd7e0a04) should show all arrows
- ~Drag the option into the preferred order by clicking and dragging the multi-directional arrow
[Demo here](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=105%3A10851&scaling=scale-down-width) by dragging the second option to the top~

**Comment by ksmoore125** [comment]
@thrijith - One of the requirements above is
> Drag the option into the preferred order by clicking and dragging the multi-directional arrow

This is not essential so if you have not started on this yet, let me know and I will create a separate ticket for this so that we can add it in at a later date.

**Comment by thrijith** [comment]
@ksmoore125 I added option to move purchase option around initially but it had some issue, due which I removed and since it was not a requirement in phase 1, I'll check back once after current task and see it can be added.

**Comment by ksmoore125** [comment]
@thrijith - We can just remove this from phase 1. I don't think it is essential so I would prefer to focus our time on other items.

**Comment by ksmoore125** [comment]
This is pending a response from the LaterPay development team in order to determine if this functionality is possible with our "Connector" &/or "On Page" integration methods.

**Comment by ksmoore125** [comment]
Closing - Won't Do see #55 for details
