### ISSUE TITLE
(6) Purchase Option: More Options

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#34]
### Sub Task of #5 

# User Story
As a Laterpay merchant, I would like to be able to configure additional options for each purchase options so that I can ensure they are using the correct payment model etc. as desired for my paywall.

# Acceptance Criteria
[Prototype](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=68%3A789)

Feature | [Single Item](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c08d75789418a0a35aee7) | [Time Pass](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c0aed69aef78d7cbd4448) | [Subscription](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c0b65dce4d38daa7cd324)  | Requirements
-- | -- | -- | -- | -- 
[Revenue Model](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c08d7693a80b56ac58c88) | ✅ | ✅ | ✅ | Only one Single Article price is allowed per paywall so this should not be accessible in other purchase option drop downs if one already exists. If an option is changed to a different revenue model, then we should keep as many settings as possible the same; any null items should default to our [default values](https://docs.google.com/spreadsheets/d/1AKCb2Mmr2767sz_VH_p2xDQW5JiUOy_GpFkaM_Hh6k0/edit?usp=sharing).
[Pay Now v Pay Later](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c08d75789418a0a35aee7) | ✅ | ✅ | | [Display additional information on hover over the ?](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e4deac32b40868aa4465c04); pricing should be re-validated if this toggle is changed
[Static Pricing v Dynamic Pricing](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c08d75789418a0a35aee7) | ✅ | | | When Dynamic Pricing is on, display a ⭐️ next to the price which also functions as a tooltip; Display additional information on hover over the ?](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e4deac3c8aae67cf9bf4df5)
[Duration](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c0aecee4ea2091b1e18a8) | | ✅ | ✅ | This should follow the same standards as the existing LaterPay plugin
Delete Purchase Option | ✅ | ✅ | ✅ |  |

**Comment by ksmoore125** [comment]
# Relevant comments:

https://github.com/laterpay/revenue-generator/issues/5#issuecomment-589136370

**Comment by ksmoore125** [comment]
_I am not sure if this is possible to change but here is a somewhat annoying item:_
**Steps to Reproduce**
- Add a new purchase option
- Set to a Time Pass or Subscription
- Adjust the duration to a number that is outside the hover area (ie: 24)

**Observed Result**
As soon as the option is changed, the "more options" menu closes

**Expected Result**
It would stay open while editing

I understand that it is closing because of where the mouse is, could we wait an extra few seconds before closing to give the person time to move their mouse back over the box?

**Comment by thrijith** [comment]
@ksmoore125 I couldn’t find an option to get the option manager stay in focus, I'll get back to this once rest of the tasks are completed.
