### ISSUE TITLE
Pricing Validation Flow

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#42]
⚠️ WIP - Needs approval from LP design team - check in with Kimberly before working on this

# Acceptance Criteria
- Ensure that the prices match with the `pay now` v `pay later` thresholds
- Ensure that the merchant is aware if their pricing structure

### Proposed Solution
Merchant Action | Plugin Action | Design
-- | -- | --
**The merchant changes the price & the price is still valid with their current `pay now` v `pay later` selection** | No action required | ✅ 
**The merchant changes the price & the price is NOT valid with their current `pay now` v `pay later` selection** | Display the `more options` menu & show the toggle changing | ![image](https://user-images.githubusercontent.com/41650164/77193580-7c446e00-6aac-11ea-987d-fc2fbef8d3e6.png)
. | Display a message that explains the price thresholds | ⚠️ 
**The merchant changes their `pay now` v `pay later` selection and the price is still valid** | No action required | ✅ 
**The merchant changes their `pay now` v `pay later` selection & the price is NOT valid with ** | Change the price to the nearest valid value (ie: if changing to `pay later` and it is a high value, set the price to $5 (the highest allowed), if changing to `pay now` and the price is too low, set the price to $1.99 (the lowest allowed) | ![image](https://user-images.githubusercontent.com/41650164/77193920-0096f100-6aad-11ea-8eb3-1782f1e876e2.png)
. | Display a message that explains the price thresholds | ⚠️

**Comment by ksmoore125** [comment]
@thrijith - Is this proposed solution possible? If so, I will work with design to get the ⚠️ items finalized. Let me know if you have any doubts or if this is not an easy solution!

**Comment by thrijith** [comment]
@ksmoore125 updated the validation issue here, for the message would this kind of notification work? It won't halt any other user action, and will give necessary info required, we can extend the time and change styling of the message if required.

Sample notification 👇 

![Screen Recording 2020-03-24 at 4 46 07 PM](https://user-images.githubusercontent.com/13589980/77420336-d9635b00-6def-11ea-96ca-317d8b3565ea.gif)

**Comment by ksmoore125** [comment]
@thrijith - That looks good; it matches the other messages I have seen in the plugin.
Error message text:
**If changing to `Pay Now` and price is too low**
> Pay Now is only available for prices set to $1.99 or higher.

**If changing to `Pay Later` and price is too high**
> Pay Later is only available for prices set to $5 or less.

**Comment by ksmoore125** [comment]
The validation does not appear to be working properly; it appears to be setting the price to $1.99 if I change the toggle.

# Scenario 1: Pay Now -> Pay Later with Valid Price
**Steps to Reproduce**
- Toggle is set to `Pay Now`
- Set the price to $5
- Change to `Pay Later`

**Observed Result**
- Price changes to $1.99
- Message says "Pay Now is only available for prices set to $1.99 or higher."

**Expected Result**
Toggle should change, price should stay at $5, no error message should be displayed

# Scenario 2: Pay Later -> Pay Now with Valid Price
**Steps to Reproduce**
- Toggle is set to `Pay Later`
- Set the price to $5
- Change to `Pay Now`

**Observed Result**
- Price changes to $1.99
- Message says "Pay Now is only available for prices set to $1.99 or higher."

**Expected Result**
Toggle should change, price should stay at $5, no error message should be displayed

# Scenario 3: Pay Later -> Pay Now with Invalid Price
**Steps to Reproduce**
- Toggle is set to `Pay Later`
- Set the price to $0.05
- Change to `Pay Now`

**Observed Result**
- Price changes to $1.99
- Message says "Pay Now is only available for prices set to $1.99 or higher."
✅ 

# Scenario 4: Pay Now Lower Price
**Steps to Reproduce**
- Toggle is set to `Pay Now`
- Set the price to $0.05

**Observed Result**
- Toggle changed to `Pay Later`

**Expected Result**
Additionally an error message (Pay Now is only available for prices set to $1.99 or higher.) should have been displayed

# Scenario 5: Pay Now -> Pay Later with Invalid Price
**Steps to Reproduce**
- Toggle is set to `Pay Now`
- Set the price to $6
- Change to `Pay Later`

**Observed Result**
- Price changes to $1.98
- Message says "Pay Later is only available for prices set to $5 or less."

**Expected Result**
Toggle should change, price should reduce to $5, error message was correct

# Scenario 4: Pay Later Higher Price
**Steps to Reproduce**
- Toggle is set to `Pay Later`
- Set the price to $6

**Observed Result**
- Toggle changed to `Pay Now`

**Expected Result**
Additionally an error message (Pay Later is only available for prices set to $5 or less.) should have been displayed

**Comment by ksmoore125** [comment]
**Product Check**
- ✅ Scenario 1: Pay Now -> Pay Later with Valid Price
- ✅ Scenario 2: Pay Later -> Pay Now with Valid Price
- ✅ Scenario 3: Pay Later -> Pay Now with Invalid Price
- ✅Scenario 4: Pay Now Lower Price
- ✅Scenario 5: Pay Now -> Pay Later with Invalid Price
- ✅ Scenario 6: Pay Later Higher Price
