### ISSUE TITLE
Published v Saved & Disabled Paywalls

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#45]
# User Story
As a LaterPay merchant, I would like to be able to clearly see the status of my paywalls so that I can know what product offerings are available to my customers.

# Acceptance Criteria
The `Revenue Generator` allows for the merchant to create paywalls with the following two statuses:
- `PUBLISHED`
  - A paywall becomes `PUBLISHED` when 
    - The merchant's account is successfully "Connected" to LaterPay
    - AND the merchant clicks `Publish` on that paywall
  - These paywalls are "live" and should be displayed to the end user
  - On the revenue dashboard, these paywalls should have a black outline and state that it is **PUBLISHED**
![image](https://user-images.githubusercontent.com/41650164/77324929-77b6ca00-6ce5-11ea-8c2d-c1fc245f0a98.png)

- `SAVED`
  - A paywall is `SAVED` if:
    - The merchant's account is not "Connected" to LaterPay
    - OR the merchant clicks `Save` on that paywall
    - OR the merchant chooses to "Publish" paywall and then chooses `Disable Paywall`
  - These paywalls are Saved and therefore all the information should be easily accessible to the merchant but they should NOT be visible to the end user
  - On the revenue dashboard, these paywalls should have a grey outline and state that they are **SAVED**
ie: Instead of **PUBLISHED** on the paywall is **SAVED** for

**Comment by ksmoore125** [comment]
Cannot test for sure until the paywalls are shown on the site.

**Comment by thrijith** [comment]
@ksmoore125 I've updated the plugin on test site, added the paywalls same as you had, can you please check if it is working for you?

**Comment by ksmoore125** [comment]
@thrijith - Let's hop on a call Mar 26 to try to figure this out. I can see the paywalls once you have looked at the site but once I uninstall and reinstall new versions I can no longer see the new paywalls I create.

Additionally, I would like it if the `Publish` button were always enabled and does the functionality in the ticket description. If you have doubts we can discuss on the call. 

I am available 7:30am-9am (GMT-05); feel free to schedule something or we can just hop on a Slack call when it is convenient.
