### ISSUE TITLE
Can't Save or Publish First Paywall

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#46]
# Can't Save or Publish
**Steps to Reproduce**
- Open plugin for the first time
- Complete the tutorial
- Set plugin to `All Posts & Pages`
- Attempt to Save or Publish

**Observed Result**
Both the Save and Publish buttons are disabled
_It appears that I need to search for a different article before it will let me save or publish_

**Expected Result**
I should be able to Save or Publish or get a warning message of some kind 

# Can't Publish
I wasn't able to click publish & connect my account until after my third paywall. 🤔

**Comment by thrijith** [comment]
@ksmoore125 
> Both the Save and Publish buttons are disabled
It appears that I need to search for a different article before it will let me save or publish

> I wasn't able to click publish & connect my account until after my third paywall. 🤔


`Save` button is disabled when `category` or `except for category` is selected in `Apply to` and no category is selected, if merchant switch backs to `all posts and pages` or `selected post or page`, then the disabled button should revert back to original state ( it had an issue, which has been fixed )

`Publish` is disabled for paywalls that aren't saved yet.

**Comment by ksmoore125** [comment]
@thrijith - 
> Publish is disabled for paywalls that aren't saved yet.

Can we adjust this so that either options is enabled and if they click `Publish` it both saves and publishes?

**Comment by thrijith** [comment]
> Can we adjust this so that either options is enabled and if they click Publish it both saves and publishes?

I have made some changes, it will now save changes as well for `Publish`, but the paywall should be saved in the first place, please let me know if that works, else having 2 separate actions might not make sense, please let me know in case of any concerns.

Thanks

**Comment by ksmoore125** [comment]
This bug appears to be resolved. I will post any additional changes to the `Save` v `Publish` functionality in #45
