### ISSUE TITLE
Purchase Option Configuration

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#5]
# User Story
As an Easy Paywall merchant, I would like to be able to customize the text and options available on my paywall so that I can ensure that it provides an exceptional experience to my specific user group.

# Description
Similar to the existing LaterPay Plugin, we will allow the merchant to sell content via single item, time pass, or subscription. However, in this plugin they will configure all pricing options in one place where they can see what the paywall will look like on one of their articles.

# Acceptance Criteria
We need to provide the following functionality
1. For each new Paywall, we pre-populate default values #29 
2. Add additional purchase options #30
3. Edit the purchase option title & description #31
4. Edit the price #32
5. Reorder the purchase options #33
6. Configure more options #34

**Comment by thrijith** [comment]
> Maximum of 1 Single Article option (see also the section about the revenue model drop down)

@ksmoore125 If an Individual option exits in the paywall should its selection be removed from the drop down?

![Screenshot 2020-02-20 at 8 50 57 PM](https://user-images.githubusercontent.com/13589980/74948983-17511600-5423-11ea-900b-f02c75af1b86.png)

If a saved time passe's dropdown is switched and set to subscription, should the existing time pass be deleted or should the selection of type be only provided to unsaved purchase options?

**Comment by ksmoore125** [comment]
> If an Individual option exits in the paywall should its selection be removed from the drop down?

Yes

> If a saved time pass's dropdown is switched and set to subscription, should the existing time pass be deleted or should the selection of type be only provided to unsaved purchase options?

The time pass would be removed and a subscription would be created. If any change is made to a saved TP or Subscription then we should display this error message: https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e4deac2497bf47c22d456e0

**Comment by thrijith** [comment]
> On hover over the star icon or the price, display a tooltip to explain dynamic pricing
[View here](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=68%3A3727&scaling=scale-down-width)

@ksmoore125 an info modal is displayed when `?` is clicked in option manager, is same output expected on hover/click fo the start icon? 
![Screenshot 2020-03-10 at 10 24 53 PM](https://user-images.githubusercontent.com/13589980/76338313-8339e680-631e-11ea-86a8-1bda568b3e74.png)

**Comment by ksmoore125** [comment]
Sorry, it looks like that screen was removed from the prototype. The star icon next to the price on the paywall (below) should display a normal tooltip (displayed on hover) with the following text:

![image](https://user-images.githubusercontent.com/41650164/76339145-b69d5680-62c7-11ea-88df-764031536665.png)

> You’re using Dynamic Pricing. The revenue generator automatically assigns a price to each article this paywall is applied to based on the amount of content the article contains.
> 
> The price for this specific article is shown here.
