### ISSUE TITLE
Paywall Intermittently not Appearing

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#50]
While testing the new plugin, I have observed it working. However, as of right now, paywalls are not appearing on my site:

**Steps to Reproduce**
- Navigate to my [Paywall Dashboard](http://kimberlystestsite.cloudaccess.host/wp-admin/admin.php?page=revenue-generator-dashboard)
- Note that I have the following 2 published paywalls
- `All Posts` -> Navigate to any post; [this one for example](http://kimberlystestsite.cloudaccess.host/?p=682)
- `Hello World` -> Navigate to [this post](http://kimberlystestsite.cloudaccess.host/?p=595)

**Observed result**
The paywall is not displayed

**Also tried:**
- Opening in an incognito window
- Logging out of WordPress and looking at the page
- Choosing `View on live post` after re-publishing the paywall

**Comment by thrijith** [comment]
@ksmoore125 There was an issue with pricing revenue for individual option, I've fixed that on the site, will update validation to make sure this doesn't happen again.

**Comment by ksmoore125** [comment]
I am still not able to view the paywalls on my test site.

**Comment by ksmoore125** [comment]
See the [comment here](https://github.com/laterpay/revenue-generator/issues/8#issuecomment-604094887); I believe that this ticket is resolved.

**Comment by ksmoore125** [comment]
This issue is resolved; all future issues with paywalls not appearing properly are tracked in https://github.com/laterpay/revenue-generator/issues/60
