### ISSUE TITLE
Connector Overlay Styling (WIP)

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#52]
# Description
We plan to change our integration to use OnPage as soon as it is ready but it looks like it may still be a month or more out therefore we should update the styling of the connector overlay to ensure that it matches as closely as possible to what OnPage will look like.

# Acceptance Criteria

Element | Description | Change needs to be made to
-- | -- | -- 
Teaser Length | Should be the entire first paragraph | Preview & Article 
Overlay blurred content behind the overlay |Should be as short as possible | Preview
Header | Should say `Support quality journalism` | Preview & Article
Header Background Color | #fff | Article
Purchase option background color |  #fff | Article
Main text color | #2e2e2e | Article
Description text color | #585858 | Article
Purchase button background color | #2e2e2e | Article
Purchase button text color | #ebebeb | Article
Purchase button hover color | #2e2e2e | Article
Purchase button hover text color | #ebebeb | Article
Link main color | #2e2e2e | Article
Link hover color | #2e2e2e | Article
Footer (Show valid payment options) | Should be turned off | Article

**Comment by ksmoore125** [comment]
@thrijith - This ticket is ready to be worked on; thanks for your patience!

**Comment by thrijith** [comment]
@ksmoore125 
Teaser Length: Currently if the post has an excerpt, then that is used for teaser, else it extracts 5% of the content or at least 10 - 15 words of the post content.


Header : Currently we have set `Keep Reading` as title in the preview, connector sets `Read Now, Pay Later` as default.

Should I keep the title as it is or change it to `Support quality journalism` in backend? `Keep Reading` would be better than suggested title considering type of merchants, please let me know in case of any concerns.

**Comment by ksmoore125** [comment]
This is something that we are discussing internally. I will move the Overlay header to a new ticket so that we can close this one out.
