### ISSUE TITLE
Exit Tour Eventually Sends you Back to the Tutorial

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#53]
**Steps to Reproduce**
- Uninstall & Reinstall / Activate the plugin
- Navigate to the Revenue Generator
- Start the Tutorial
- A few steps in, click `Exit Tour` in the bottom right corner
- Create a Paywall
- From the Dashboard, click `New Paywall`

**Observed Result**
The tutorial starts again

**Desired Result**
The tutorial should not start (after the first visit to the plugin) unless you click `Tutorial` on the Dashboard

**Comment by thrijith** [comment]
Unable to replicate issue using described steps, @ksmoore125 please refer [this](https://drive.google.com/open?id=1OTLpmemQ3KOhEqNSzyrHRLriwD1lb8jh)

**Comment by ksmoore125** [comment]
Cannot reproduce.
