### ISSUE TITLE
Remove Ability to Reorder Paywall & Mimic Connector Default Order

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#55]
# Details
Unfortunately our connector integration method does not support the ability to customize the order of items in the paywall therefore we need to remove this functionality from the UI.

I will be creating a ticket for us to add this in the future and at that point we will add it back to the paywall.

# Acceptance Criteria
- Hide the up and down arrows for the payment options so that the merchant does not think they can reorder the purchase options
- Automatically display them in the following order so that it matched what will be displayed by connector on their article:
> The database query orders them by Sales Model (single purchases first, then timepasses, then subscriptions), and then secondarily by title and price.

**Comment by thrijith** [comment]
> The database query orders them by Sales Model (single purchases first, then timepasses, then subscriptions), and then secondarily by title and price.

@ksmoore125 I've removed option to order the purchase options.

> and then secondarily by title and price.

@ksmoore125 can you please provide more details on the sorting done by connector, to make sure backend preview, reorders items as they would appear in connector eventually.

**Comment by ksmoore125** [comment]
I have asked for additional clarification from the team [here](https://laterpay.slack.com/archives/C06L9FN6N/p1585327680019600).

**Comment by ksmoore125** [comment]
@thrijith - The order is:

1. Single Article option (if applicable)
2. Time Pass options(s) (if applicable)
  - order by title asc, price asc
3. Subscription options(s) (if applicable)
   - order by title asc, price asc

> the relevant code is here:
https://github.com/laterpay/connector/blob/develop/connector/connector/models/purchase_option.py#L204-L217
And the sort_priority is set for each SalesModel type approximately here:
https://github.com/laterpay/connector/blob/develop/connector/connector/purchase_options/base.py#L230

**Comment by ksmoore125** [comment]
@thrijith - This appears to work properly but the items are only reordered after I Save or Publish the paywall. Would it be possible to have them reorder themselves after the merchant stops updating them (ie: when the more options dialog closes or after the title or price is updated?)

**Comment by thrijith** [comment]
> This appears to work properly but the items are only reordered after I Save or Publish the paywall. Would it be possible to have them reorder themselves after the merchant stops updating them.

Sure, I'll take a look, I initially thought of adding in frontend so the change is visible, but reverted since we will have to remove all code once connector supports the option to move purchase option around.

**Comment by ksmoore125** [comment]
Additionally, after looking at it, it appears that the order is not quite right.

**Actual Result**
![image](https://user-images.githubusercontent.com/41650164/78158010-58ffb400-7406-11ea-80f9-81568d633a6f.png)

**Expected Result**
1. Single Article option (if applicable) ✅ 
2. Time Pass options(s) (if applicable)
   - order by title asc, price asc
3. Subscription options(s) (if applicable)
   - order by title asc, price asc

_In this case since the titles for the two time passes and two subscriptions are the same, the order should be:_

**Comment by thrijith** [comment]
@ksmoore125 The sorting should now be visible to merchant when they add new option, change price, saving/publishing the paywall. 

The title based sorting doesn't seem to work in connector right now, please check below screenshot for time passes with same price but with different title.

![Screenshot 2020-04-02 at 12 57 00 PM](https://user-images.githubusercontent.com/13589980/78225362-b7e92a00-74e7-11ea-8db1-1b850b020ed2.png)

Prices ASC sorting is working as expected so that backend sorting is added for that only, updated on your demo site, please let me known in case of any concerns. Following is connector options sorted by price different title.

![Screenshot 2020-04-02 at 1 20 02 PM](https://user-images.githubusercontent.com/13589980/78225452-de0eca00-74e7-11ea-9397-9fda0add9f75.png)

**Comment by ksmoore125** [comment]
@thrijith - I could not get clarification from our development team and I don't think this is a big priority so let's set the preview order so that it is as follows. We can work to get additional clarification if a merchant runs into an issue.

- Single Article option (if applicable) ✅
- Time Pass options(s) (if applicable)
  - order by **price** asc, title asc
- Subscription options(s) (if applicable)
  - order by **price** asc, title asc

**Comment by thrijith** [comment]
@ksmoore125 I think the price based sorting with in multiple time passes and subscriptions is working as expected, can you please add steps to replicate issue you are facing?
