### ISSUE TITLE
Allow for Reordering Items in the Purchase Overlay

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#56]
This feature was originally included in the plugin but we removed it since this is not supported by Connector or OnPage.

References:
- https://github.com/laterpay/revenue-generator/issues/5
- https://github.com/laterpay/revenue-generator/issues/33
- https://github.com/laterpay/revenue-generator/issues/55

**Comment by thrijith** [comment]
Reminder: Use code from 1acf799896434941e228089bf6be797ba8d2aade to add them back

**Comment by ksmoore125** [comment]
[Moved to Jira](https://laterpay.atlassian.net/browse/ROADMAP-69)
