### ISSUE TITLE
Paywalls not Displaying Appropriately on Articles

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#60]
Status | Paywall Summary | View on Live Post | Notes
-- | -- | -- | --
✅ | ![image](https://user-images.githubusercontent.com/41650164/77692795-481df100-6f75-11ea-8882-2fff1979f343.png) | ![image](https://user-images.githubusercontent.com/41650164/77692819-4f44ff00-6f75-11ea-9841-c902eb1ca04f.png) | 
❌ | ![image](https://user-images.githubusercontent.com/41650164/77692938-83202480-6f75-11ea-86e1-c3e38f79184d.png)| ![image](https://user-images.githubusercontent.com/41650164/77692948-89ae9c00-6f75-11ea-83ca-b0daea81d3a9.png) | There is no paywall on this single article; other posts appear to be ok ![image](https://user-images.githubusercontent.com/41650164/77693030-aea30f00-6f75-11ea-8a21-dc4539504f06.png)
❌   | ![image](https://user-images.githubusercontent.com/41650164/77693232-02155d00-6f76-11ea-8f46-8a77051eeeaa.png) | ![image](https://user-images.githubusercontent.com/41650164/77693261-0a6d9800-6f76-11ea-8602-81d9a88fa9c3.png) | A paywall is displayed but it has a different single article price than what I set up for the `Tutorials` Category
✅ | ![image](https://user-images.githubusercontent.com/41650164/77693516-79e38780-6f76-11ea-9170-4a04770f6680.png) | ![image](https://user-images.githubusercontent.com/41650164/77693899-1efe6000-6f77-11ea-8d6f-1413fd17edc0.png) | This single article appeared to display ok

**Comment by thrijith** [comment]
@ksmoore125 Fixed issue with connector pricing in 2nd case, I am checking issue with category pricing issue reported in case 3.

There was also an issue with `Pay Later` pricing from connector, warning `Pay Later price must be between 0.05 and 4.99.`, so we should set the max pay later price to `4.99`, I have updated the code accordingly.

Refer: https://docs.laterpay.net/connector/configuration/connector_admin_interface/#payment-models

**Comment by thrijith** [comment]
@ksmoore125 Fixed issue with category price not being applied, can you please check and confirm on your site? I have added latest zip on the site.
