### ISSUE TITLE
Modal Updates

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#69]
## Acceptance Criteria
**Update all modals to match [detailed design specifications](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e4deac32b40868aa4465c04)**
 - Modal fonts and paddings not consistent
 - Missing lightbox around the referring component ([here](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e4deac32b40868aa4465c04))
  - Ensure there are no closing "X" icons
  - Footer should be greyed out

**Details**
- Subscription Warning ([detailed design specifications](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e4deac2497bf47c22d456e0))
  - All of the above +
    - Alert icon circle line ([here](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e4deac2497bf47c22d456e0))
    - Button width ([here](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e4deac2497bf47c22d456e0))
- Static Pricing and Dynamic Pricing popup ([detailed design specifications](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e4deac3c8aae67cf9bf4df5))
  - All of the above
- Connect Account page ([here](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c0fc658245792d0cd2a6f))
  - Left align the Merchant ID & API key fields
  - Update padding etc to match design
  - Underneath the heading, add a paragraph which says:
> Unsure where to find this information? [Click here](https://support.laterpay.net/what-is-my-laterpay-merchant-id-api-key-and-where-can-i-find-them).  
- Connect Account error page ([here](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e4deac29f5b227e094cde55))
  - Update the paragraph so that it reads as described below and where `try again` should reload the Connect account page
> ... Please [sign up here](url), [try again](url), or contact...

**Comment by ksmoore125** [comment]
![image](https://user-images.githubusercontent.com/41650164/78712100-b2238800-78dd-11ea-8b6e-938fdf2b6563.png)

- Padding still not consistent (especially the bottom; padding should be 54px per the design specs)
- As shown in the image above, when you click on either of the two (?)'s there is an extra white line that shows up in the more options menu (in this screenshot it is below the purchase option type selection)
- Clicking anywhere on the screen should also close this; not only clicking on the (?)
- Footer and Article search should still be visible, just greyed out as shown in the design specs
- Time Pass / Subscription warning is no longer appearing
- Connect Account page: `click here` should be styled like the other hyperlinks, not blue & update padding (especially around the new paragraph)
- While trying to connect your account, the loading screen has the new Connect account paragraph and shouldn't
- Trying to connect account after it fails the first time goes directly to `Something went wrong`

**Comment by thrijith** [comment]
> Time Pass / Subscription warning is no longer appearing

Unable to replicate this fixed rest of the mentioned issues.

**Comment by ksmoore125** [comment]
- Padding still not consistent (especially the bottom; padding should be 54px per the design specs) ✅ 
- As shown in the image above, when you click on either of the two (?)'s there is an extra white line that shows up in the more options menu (in this screenshot it is below the purchase option type selection) ✅ 
- Clicking anywhere on the screen should also close this; not only clicking on the (?) ❌
![image](https://user-images.githubusercontent.com/41650164/78825121-08a7c980-79a5-11ea-8752-e4fc8714e586.png)
- Footer and Article search should still be visible, just greyed out as shown in the design specs ❌
  - This appears to work for the two toggle (?)s but does not happen for the other modals (subscription warning or Save / Publish flows)
- Time Pass / Subscription warning is no longer appearing ❌ 
Steps to Reproduce:
  - Delete the time pass option (note that the warning appears)
  - Add the time pass option back
  - Delete the time pass (note that the warning does not appear)
- Connect Account page ⚠️ 
  - click here should be styled like the other hyperlinks, not blue ✅ 
  - update padding (especially around the new paragraph) ❌ 
![image](https://user-images.githubusercontent.com/41650164/78823905-1f4d2100-79a3-11ea-971a-1f1935dc3375.png)
- While trying to connect your account, the loading screen has the new Connect account paragraph and shouldn't ✅ 
- Trying to connect account after it fails the first time goes directly to Something went wrong ✅

**Comment by thrijith** [comment]
> Time Pass / Subscription warning is no longer appearing 

This was only showing warning when saved options were edited/deleted, updated the check, now it will show warning on time passes and subscriptions irrespective of the saved status.

**Comment by ksmoore125** [comment]
A couple nit-pick-y things:
1. On the Connect Account modal, can we please center the new (highlighted) paragraph?
![image](https://user-images.githubusercontent.com/41650164/78933973-bbdcf500-7a6f-11ea-9f25-4d4a8f64ce78.png)

2. When I copy & paste my Merchant ID & API key in, the new paragraph (highlighted above) shifts to the right a little bit which is distracting

Before | After
-- | --
![image](https://user-images.githubusercontent.com/41650164/78934055-e5961c00-7a6f-11ea-85fd-c5c00b932541.png) | ![image](https://user-images.githubusercontent.com/41650164/78934136-052d4480-7a70-11ea-878f-0f551ff75997.png)
