### ISSUE TITLE
Content Selection

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#7]
# User Story
As a merchant I do NOT want to have to define the paywall on every individual article therefore I would like to be able to define this by groups of content so that I get safe time and effort.

# Acceptance Criteria
[View prototype flow here](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=68%3A7757&viewport=906%2C-505%2C0.027233021333813667&scaling=scale-down-width)
- Merchant should be able to name the paywall
- Merchant should be able to select if they would like their content displayed on
  - Individual Post
  - Category
  - Except for Category
  - All pages & posts
- Merchant should be able to select the article(s) or categories(s)
- We should prevent them from publishing conflicting paywalls (see #35 for details)

### Design Specs
[Select dimension](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e5d4b554085d175a85a8aed)
[Select categories](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c0e9bd5d27490decbe38c) & [Selected categories](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c0e9b76e12eb2f2ad67f3)

**Comment by thrijith** [comment]
https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c0e9b2b16c49590a9ef0b

@ksmoore125 What actions should both options do when selected? 

> Replace [Paywall Name 2] with [Paywall 1] on [Article Name]
Should the access provided to an article in paywall be changed?

> Keep [Paywall Name 2] on [Article Name], making it an exception.
Not completely clear on this one.

Based on above scenario, a conflict would occur on most case when a paywall that applies to all content exists.

- We could allow merchant to create this paywall without conflict, but inform/warn that the category based paywall would take a higher priority.
- We could exclude categories from search that have a paywall attributed to them already thus avoiding that conflict.
- Right now, when an article is searched for preview, if it has a paywall directly providing access to it, then the paywall is loaded.

Based on current paywalls created on frontend we could check if a paywall exits for the content in order of priority, please let me know if that would or if some case that couldn’t be handled in this workflow.

**Comment by ksmoore125** [comment]
[I have created a document outlining the different scenarios](https://rtcamp.slack.com/archives/GA2P84GBZ/p1583519491004200?thread_ts=1583432129.002800&cid=GA2P84GBZ) we will move the discussion here and once we have a decision I will update this ticket as needed.

**Comment by ksmoore125** [comment]
The only item is https://github.com/laterpay/revenue-generator/issues/39
