### ISSUE TITLE
LaterPay Account

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#8]
# User Story
As a merchant I would like to be able to go live so that I can earn revenue therefore I need an easy way to link to my LaterPay account.

# Acceptance Criteria
- Clicking Save should: 
  - Save their paywall settings
  - Not make the paywall visible to their users
  - Redirect them to their Paywall Dashboard (where the newly saved paywall should now be visible)
- Clicking Publish should:
  - If a merchant **_has not_** already been verified then:
[View here](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=373%3A11711&viewport=906%2C-505%2C0.027233021333813667&scaling=scale-down-width)
    - Save their paywall settings
    - Ask them to Create or Connect their account
      - If they click to create an account then we open the following URLs in a new tab
        - US: https://web.uselaterpay.com/dialog/entry/?redirect_to=/merchant/add/#/signup
        - ~EU: https://web.laterpay.net/dialog/entry/?redirect_to=/merchant/add/#/signup~
      - If they choose to sign in, then in the background we run a test purchase to verify that their account is active (see below for details)
         - If successful: Show a success screen `pending`
         - If un-successful: Ask them to create a LaterPay account or contact us `pending`
  - If a merchant **_has_** already been verified then:
    - Save their paywall settings
    - Make the paywall visible to their users
   - Display a success screen `pending`
    - Redirect them to their Paywall Dashboard (where the newly saved paywall should now be visible)

### Technical Details
**To run a test purchase:**
- Make a request to `/dialog/add` ([documentation here](https://docs.laterpay.net/platform/dialogs/sales/add/)) with the following parameters:
  - `article_id` = wordpress_plugin_account_verification
  - `pricing` = 0
  - `title` = Account Verification Purchase
  - `url` = `the merchant's domain`
  - `renewable` = 0
  - `cp`, `hmac`, `ts`
- The resulting call will return a redirect to a new url. Load this URL and search for a `purchaseURL:` json object.
- POST empty JSON `{}` to this URL to complete the transaction. 

### Design Specs
[Signup or Connect Account](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c0fc668c74d8e347c82db)
[Connect](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c0fc658245792d0cd2a6f)
[Loading 1](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c10c4034abf8d20317088) [Loading 2](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c10c4292e3b8b99f1428a) [Loading 3](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c10c4cf17278c82b2d6e6)
[Error Message](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e4deac29f5b227e094cde55)
[Publish Successful](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c1137e0ddc3910823bc41)

**Comment by thrijith** [comment]
@ksmoore125 Where should `Learn more` in [account activation](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c0fc668c74d8e347c82db) take the merchant to?

On `Signup` it will open a new tab and allow merchant to create account, the action should also allow user to input credentials in order to activate the account.

I see two modals with different button and links, is it for each action?

https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c0fc61858a5b453cb38d1

https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c0fc658245792d0cd2a6f

**Comment by ksmoore125** [comment]
`Learn more` should open this in a new tab: https://support.laterpay.net/what-is-laterpay

We have two potential flows:

- [Signup](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c0fc61858a5b453cb38d1): A new merchant who does not have a LaterPay account
This merchant will need to create their account before they can go live

- [Signin](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c0fc658245792d0cd2a6f): For an existing merchant so that we can verify their account is set up correctly
We don't actually need their credentials since connector uses the domain; here we are just buying time while we perform a test purchase behind the scenes to make sure that everything will work properly if the paywall is displayed to customers (see the `Technical Details` section above)

**Comment by ksmoore125** [comment]
> ASSUMPTION: We will store if a merchant has been "verified"

- Merchant Clicks `Publish`
  - Merchant verified = true ✅ we publish
  - Merchant verified = false
We show the [connect / signup screen](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c0fc668c74d8e347c82db)
    - They click `Signup`: We [open LaterPay](https://web.uselaterpay.com/dialog/entry/?redirect_to=/merchant/add/#/signup) in a new tab so that they can register & in WordPress, we change to the `Connect` dialog 👇 
    - They click `Connect Account`: We [open the Connect dialog](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c0fc658245792d0cd2a6f)**
Where we run the test purchase in the background
      - Connect succeeds: We publish the paywall and show the [success screen](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c1137e0ddc3910823bc41)
      - Connect fails: We show the [error page](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e4deac29f5b227e094cde55)

** If on the `Connect` dialog, they click `Don't have an account? Signup` then We [open LaterPay](https://web.uselaterpay.com/dialog/entry/?redirect_to=/merchant/add/#/signup) in a new tab and leave WordPress on the Connect screen

**Comment by ksmoore125** [comment]
Updated the requirements: We are not supporting the EU in this version

**Comment by ksmoore125** [comment]
Will wait to product check until https://github.com/laterpay/revenue-generator/issues/46 is complete.

**Comment by ksmoore125** [comment]
**Product Check**
- Clicking Save should:
  - ✅ Save their paywall settings
  - ~Not make the paywall visible to their users~ (will test with #50)
  - ✅ Redirect them to their Paywall Dashboard (where the newly saved paywall should now be visible)
- Clicking Publish should:
  - If a merchant has not already been verified then:
    - ✅ Save their paywall settings
    - ✅ Ask them to Create or Connect their account
      - ✅ If successful: Show a success screen
      - ❌ If un-successful: Ask them to create a LaterPay account or contact us
  - If a merchant has already been verified then:
    - ✅ Save their paywall settings
    - ~Make the paywall visible to their users~ (will test with #50)
    - ✅ Display a success screen

Everything looks good except the validation is not working as expected.
**Steps to Reproduce**
- Choose to Connect account
- Enter invalid credentials (ie: I used the Merchant ID for both the Merchant ID & API key)
**Observed Result**
The validation passes
**Expected Result**
Validation fails & I get an error message + the chance to try again

**Comment by thrijith** [comment]
> If un-successful: Ask them to create a LaterPay account or contact us

@ksmoore125 Current verification process only included verification of the domain
validity for connector credentials isn't added currently, should it me similar to current verification done in https://github.com/laterpay/laterpay-wordpress-plugin ?

**Comment by ksmoore125** [comment]
I [started a thread](https://rtcamp.slack.com/archives/GA2P84GBZ/p1585239247002400) here so that we can discuss in more detail without cluttering the ticket.

**Comment by ksmoore125** [comment]
@thrijith - While testing the newest version of the plugin, I testing using a different LaterPay account which was valid and enabled for Connector but with a different website. When doing this, the validation passed but the overlay was not displayed on the site. This should have failed validation.

**Comment by thrijith** [comment]
@ksmoore125 The credentials were valid but tested on your current demo site is that correct?
There are 2 tests though independent, if one fails the process fails.

Credentials are tested differently, so your valid credentials test pass, then it moves on to see if current domain is allowed from connector.

We initially tried to the test purchase but that didn't, that is when shifted to domain and account credential validation.

**Comment by ksmoore125** [comment]
@thrijith - Correct, with the following credentials, the credentials should pass but the domain should fail:
Merchant ID: `rqfwaRSppyJgCUHQKb6TTU`
API Key: `c32b177ec9744a14be9a4b8809e02738`

**Comment by ksmoore125** [comment]
Per the [conversation here](https://laterpay.slack.com/archives/C02JCERA4/p1585588680007400?thread_ts=1584038794.010100&cid=C02JCERA4), the scenario above should not occur with a real merchant therefore this ticket is approved as-is. We can address at a later date if a real merchant experiences issues.
