### ISSUE TITLE
Dashboard Design Feedback R2

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#82]
# Acceptance Criteria
1. Make the thickness of the `Sort by` underline the same as the `Search` underline
2. Make the font of both the `Search` and `Sort by` weight 400
3. Make the font of both the `Search` and `Sort by` left aligned so that it is even with the edge of the underline
4. Make the border of the paywall preview 2px
5. Adjust the paywall preview so that it is a fixed width of 20em
6. Adjust the padding around the `Tutorial` button so that the space to the right = the space below
![image](https://user-images.githubusercontent.com/41650164/79497072-b7bf5300-7fec-11ea-9f5e-3f4c73172414.png)

7. Move the `Powered by LaterPay` up so that the bottom of this is even with the bottom of the `Tutorial` button
![image](https://user-images.githubusercontent.com/41650164/79497411-3d430300-7fed-11ea-932c-7d0ad38f084d.png)

**Comment by ksmoore125** [comment]
I have marked this as blocked because the design team is currently working on other updates to the Dashboard so at this point I am not sure that it makes sense to address these; I believe we should wait and make all the changes as once.

**Comment by milindmore22** [comment]
Subtask: Apply similar changes to Contribution Dashboard #93

**Comment by ksmoore125** [comment]
**Product Check Notes:**
_Checked in chrome incognito window_

1. ✅ Make the thickness of the Sort by underline the same as the Search underline

2. ✅ Make the font of both the Search and Sort by weight 400

3. ✅ Make the font of both the Search and Sort by left aligned so that it is even with the edge of the underline

4. ✅ Make the border of the paywall preview 2px

5. ❌ Adjust the paywall preview so that it is a fixed width of 20em

6. ✅ Adjust the padding around the Tutorial button so that the space to the right = the space below

7. ❌ Move the Powered by LaterPay up so that the bottom of this is even with the bottom of the Tutorial button

**Comment by milindmore22** [comment]
Hello @ksmoore125 

I have some doubts regarding feedback 5. and 7.

5. Do you also want height to be same as per [design](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e9e1de8487f967d69e36fb6)? or should I keep current height which is 300px

7.  Currently Power by Laterpay is aligned to Tutorial buttons bottom line as mentioned in task description screenshot, do you want it to be aligned with button text (green in new screenshot )
Also do you want Power by Laterpay to be sticky? like Tutorial button (Always shown on screen )

![image](https://user-images.githubusercontent.com/1132541/81537003-2395a100-938a-11ea-8158-a9f7103236c5.png)

**Comment by ksmoore125** [comment]
@milindmore22 -

5. Please update the top & bottom padding so that they match the design but the height should not be fixed (in case they have more than 2 or 3 purchase options)

6. Your screenshot looks correct & yes please make it sticky. Here is what I see (even in an incognito window):

![image](https://user-images.githubusercontent.com/41650164/81566910-2a5bee00-9361-11ea-947e-395005047c2a.png)

![image](https://user-images.githubusercontent.com/41650164/81566947-36e04680-9361-11ea-922c-c8fcbf7be98c.png)

**Comment by ksmoore125** [comment]
@milindmore22 - The width of the paywall preview on the dashboard still does not appear to be a fixed width; it is changing sizes as I adjust the width of my browser.

Item 6 is resolved though.
