### ISSUE TITLE
Paywall Saved (not Published) after Clicking Publish

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#89]
**Use Case**
As a new merchant, I may want to create several paywalls in a row without viewing them or the paywall dashboard so that I can get it done ASAP.

**Steps to Reproduce**
- Set up a new paywall
- Configure as desired
- Click `Publish`
- Once you view the Success screen (below) click the `X` to close the modal
![image](https://user-images.githubusercontent.com/41650164/79888071-874b3080-83c1-11ea-991f-f9a19b1a9d11.png)

**Expected Result**
The paywall was published successfully

**Observed Result**
The next time I visit the Paywall Dashboard, I see that paywall appears to have been `Saved` and not `Published`

**Comment by milindmore22** [comment]
@ksmoore125 I am unable to reproduce this issue, can you please help with specific steps to follow.

**Comment by ksmoore125** [comment]
Unable to reproduce

**Comment by ksmoore125** [comment]
As you can see above, I closed because I could not reproduce. Then immediately after closing, it happened again. I have since been unable to reproduce.
