### ISSUE TITLE
Paywall Dashboard

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#9]
# User Story
As a merchant I would like to be able to easily view all of my saved paywalls so that I can ensure, at a glance, that my site is set up as desired.

# Acceptance Criteria
[Prototype here](https://www.figma.com/proto/3INU28Yy8nRuCjnBiLtxsf/0122020_WPP?node-id=68%3A9564&viewport=906%2C-505%2C0.027233021333813667&scaling=scale-down-width) | [Design Specs here](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c11377857488b74fedca0)
- On future visits to the plugin, the primary landing page should be the Paywall Dashboard
- From the dashboard, the merchant should be able to:
  - Sort their paywalls by priority*, date created, date last modified, or alphabetically _(If this is a significant effort, we can remove from scope and move to a future version if requested)_
     - ~`Priority` should be the default sort order and will be determined as follows:
Single Item (by Single Article (last_modified desc), Category (last_modified desc), Entire Site (last_modified desc)~
  - Search their paywalls _(If this is a significant effort, we can remove from scope and move to a future version if requested)_
  - Add a new paywall
  - View a summary of their existing paywalls with a snapshot of the paywall, as well as a written summary of the content definition

*Priority items are moved to #38

**Comment by ksmoore125** [comment]
@thrijith - I am not sure if this is the best place to put this, but here is the [updated design for `Add Paywall` functionality](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e667c32596188134ed866d1). Let me know if the tooltip is an issue and I will ask about moving the text to the main screen, near the browser icons.

**Comment by ksmoore125** [comment]
Updated to include the `Priority` sort order as proposed [here](https://docs.google.com/document/d/1V3a39WWVQOfpxCBriw0zJw1qd4I1_jlvgAxalfL_DKc/edit?disco=AAAAJQxbwuQ).

**Comment by ksmoore125** [comment]
**Product Check**
- ✅ On future visits to the plugin, the primary landing page should be the Paywall Dashboard 
- ✅ Sort their paywalls by priority*, date created, date last modified
- ✅ Add a new paywall
- ❌ Search their paywalls 
- ❌ View a summary of their existing paywalls with a snapshot of the paywall, as well as a written summary of the content definition

## Search paywalls
**Steps to Reproduce**
- Attempt to search for a paywall
- See the potential results in the dropdown
- Click one
**Observed Result**
Nothing happens
**Expected Result**
You can select and option and view that paywall on the dashboard page

## Paywall Snapshots
Current | Design
-- | --
![image](https://user-images.githubusercontent.com/41650164/77583972-fcedda80-6eaf-11ea-8ac7-00aaf7d625dd.png) | ![image](https://user-images.githubusercontent.com/41650164/77583934-e8114700-6eaf-11ea-9aeb-b26983722370.png) [here](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e3c11377857488b74fedca0)

**Comment by thrijith** [comment]
> #### Search paywalls
> You can select and option and view that paywall on the dashboard page

I've kept the paywall search similar to paywall content search, please refer this [video](https://drive.google.com/open?id=1LvYkW7erxV2SHtA4_ln_Fr04smAK-dMA) for the same.

> #### Paywall Snapshots
@ksmoore125 I've fixed issue on a screen size found while testing, can you please check again and let me know if it is working as expected for you? You can check tested device screenshots [here](https://drive.google.com/open?id=1TYD_7qd7bt9qpwQvWTf2n9NdFlquDzNe).

**Comment by ksmoore125** [comment]
Please [see video](https://drive.google.com/file/d/15dZbLCFS3K_dFdSYxgDrj3Rn-jjkHeLj/view?usp=sharing) of the two above issues.

**Comment by thrijith** [comment]
Styling was handling device with standard size from tablet to desktop, update styling to handle overflow issue seen above and fixed issue with paywall search item selection, @ksmoore125  I have updated the plugin on your test site, can you please verify if it is working for you as expected?

**Comment by ksmoore125** [comment]
@thrijith - These appear to be resolved in the newest version. Thanks!
