### ISSUE TITLE
[CONTRIBUTIONS] Update Welcome Screen

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#90]
# User Story
As a Revenue Generator merchant, I have likely installed the plugin for one of two primary reasons, to set up a paywall or to request contributions. We should make these features apparent right off the bat so that the merchant has a clear place to start and so that we can guide them through the process.

# Acceptance Criteria
Make the following updates to the Revenue Generator Welcome Screen
- Update the text to match the mockup (there are minor changes throughout the text)
- Change the question / panels so that the merchant is choosing between `Create Contributions` and `Create Paywall` (see below for more details)
- Text & Designs should come from [the detailed design specs here](https://xd.adobe.com/view/a9c3cfb2-0efc-4d74-b792-3383ce0918fa-fc90/screen/c8c9d1d8-7a1d-442b-a35e-afe82297a92f/Welcome-Page)

# User Flow
- Merchant views Welcome Screen
  - Merchant chooses `Create Paywall`
    - We take them to the new Paywall intro screen (https://github.com/laterpay/revenue-generator/issues/91)
    - No other changes to the paywall flow
  - Merchant chooses `Create Contributions`
    - We take the to the Create Contribution screen (no tutorial)
  - As soon as the merchant has left the Welcome Screen, the other sidebar items should appear

**Comment by milindmore22** [comment]
Hello @ksmoore125 

![image](https://user-images.githubusercontent.com/1132541/80396033-ae2dc900-88d1-11ea-86e2-73bfcf2b21f9.png)

I am unable to download Assets ( Icons ) For contribution and Paywall can you please look into it.

**Comment by ksmoore125** [comment]
See the comments & attachments [here](https://rtcamp.slack.com/archives/GA2P84GBZ/p1588009935001900?thread_ts=1588004730.000800&cid=GA2P84GBZ)
