### ISSUE TITLE
[CONTRIBUTIONS] Contributions Dashboard

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/revenue-generator#93]
# User Story
As a merchant, I would like to be able to see all of the contributions dialogs that I have generated so that I can reuse the code in other places without having to generate a new dialog.

# Acceptance Criteria
- As soon as a merchant has passed the Welcome screen, we should display both "Paywalls" (used to be Dashboard) and "Contributions" in the WordPress sidebar
  - Clicking "Contributions" should take them to the new Contributions Dashboard
- Dashboard should perform all of the following behaviors and[ match the detailed design specs here](https://xd.adobe.com/view/a9c3cfb2-0efc-4d74-b792-3383ce0918fa-fc90/screen/de75b3dd-1a4a-4312-a544-2e0d65524887/Contributions-board/):
  - Display an archive of all created dialogs
  - Allow the merchant to create a new Contribution
  - `NICE TO HAVE` The ability to search by the campaign name (should mimic the paywall dashboard search)
  - `NICE TO HAVE` Allow the merchant to sort the Paywalls either by `Newest First` (default) or `Oldest First`
- Display an empty state screen in case there are no contributions created. This screen should match the [Paywall empty state screen](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e945accaf991f7cdbd35b2d) but with the following text:
> Welcome back!
> Are you ready to get started?
`Create your first Contribution Dialog`
- In case the Contributions Dashboard is empty, we should include an [empty state screen similar to the one for the Paywall Dashboard](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e945accaf991f7cdbd35b2d). For the Contributions Dashboard, the copy should read:
> 
- IMPORTANT: Merchant cannot edit a contribution once it has been created (since that wouldn't edit the shortcode and could be very confusing) therefore if they click on an existing contribution, we should[ simply copy the shortcode to their clipboard](https://xd.adobe.com/view/a9c3cfb2-0efc-4d74-b792-3383ce0918fa-fc90/screen/70b20969-4169-4a08-8ea1-30c13097f373/4h-Done) as is done when they click the `Generate and copy code` button

**Comment by ksmoore125** [comment]
1. Remove `Priority` from the SORT BY options since this is not relevant for Contributions
2. Ensure that changes made to the paywall dashboard (#82 ) are also made to this dashboard
3. Ensure that the `thank you page URL` is displayed properly if it is long (see below)

![image](https://user-images.githubusercontent.com/41650164/80987870-4fe47700-8df8-11ea-90c9-d30f4fbb0740.png)

**Comment by milindmore22** [comment]
I will cover Contribution Dashboard feedback in ticket #82
